/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.11
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActivesessionResponseCompoundApikey } from './activesession-response-compound-apikey';
// May contain unused imports in some cases
// @ts-ignore
import { ActivesessionResponseCompoundUser } from './activesession-response-compound-user';

import { DefaultObject } from '../base'

/**
 * 
 * @export
 * @interface ActivesessionResponseCompoundAllOf
 */
export interface ActivesessionResponseCompoundAllOf {
    /**
     * An array of permissions granted to the user or api key
     * @type {Array<number>}
     * @memberof ActivesessionResponseCompoundAllOf
     */
    'a_pkiPermissionID': Array<number>;
    /**
     * 
     * @type {ActivesessionResponseCompoundUser}
     * @memberof ActivesessionResponseCompoundAllOf
     */
    'objUserReal': ActivesessionResponseCompoundUser;
    /**
     * 
     * @type {ActivesessionResponseCompoundUser}
     * @memberof ActivesessionResponseCompoundAllOf
     */
    'objUserCloned'?: ActivesessionResponseCompoundUser;
    /**
     * 
     * @type {ActivesessionResponseCompoundApikey}
     * @memberof ActivesessionResponseCompoundAllOf
     */
    'objApikey'?: ActivesessionResponseCompoundApikey;
    /**
     * An Array of Registered modules.  These are the modules that are Licensed to be used by the User or the API Key.
     * @type {Array<string>}
     * @memberof ActivesessionResponseCompoundAllOf
     */
    'a_eModuleInternalname': Array<string>;
}
/**
 * A ActivesessionResponseCompoundAllOf Object with automatic temp default value
 * Use this object only for create an empty object to assign a response from server
 * @export 
 * @class DefaultObjectActivesessionResponseCompoundAllOf
 */
export class DefaultObjectActivesessionResponseCompoundAllOf extends DefaultObject {
   a_pkiPermissionID:Array<number> = []
   objUserReal:Partial<ActivesessionResponseCompoundUser> = {}
   objUserCloned?:Partial<ActivesessionResponseCompoundUser> = undefined
   objApikey?:Partial<ActivesessionResponseCompoundApikey> = undefined
   a_eModuleInternalname:Array<string> = []
}


