/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApikeyRequestCompound } from './apikey-request-compound';

/**
 * Request for POST /2/object/apikey
 * @export
 * @interface ApikeyCreateObjectV2Request
 */
export interface ApikeyCreateObjectV2Request {
    /**
     * 
     * @type {Array<ApikeyRequestCompound>}
     * @memberof ApikeyCreateObjectV2Request
     */
    /*'a_objApikey': Array<ApikeyRequestCompound>;*/
    'a_objApikey': Array<ApikeyRequestCompound>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A ApikeyCreateObjectV2Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectApikeyCreateObjectV2Request
 */
export class DataObjectApikeyCreateObjectV2Request {
   a_objApikey:Array<ApikeyRequestCompound> = []
}

/**
 * @export 
 * A ApikeyCreateObjectV2Request Validation Object
 * @class ValidationObjectApikeyCreateObjectV2Request
 */
export class ValidationObjectApikeyCreateObjectV2Request {
   a_objApikey = {
      type: 'array',
      minItems: 1,
      required: true
   }
} 


