/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApikeyRegenerateV1ResponseAllOf } from './apikey-regenerate-v1-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { ApikeyRegenerateV1ResponseMPayload } from './apikey-regenerate-v1-response-mpayload';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';

/**
 * @type ApikeyRegenerateV1Response
 * Response for GET /1/object/apikey/{pkiApikeyID}/regenerate
 * @export
 */
export type ApikeyRegenerateV1Response = ApikeyRegenerateV1ResponseAllOf & CommonResponse;


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectApikeyRegenerateV1ResponseMPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectApikeyRegenerateV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'

/**
 * @export 
 * A ApikeyRegenerateV1Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectApikeyRegenerateV1Response
 */
export class DataObjectApikeyRegenerateV1Response {
    mPayload:ApikeyRegenerateV1ResponseMPayload = new DataObjectApikeyRegenerateV1ResponseMPayload()
    objDebugPayload?:CommonResponseObjDebugPayload = undefined
    objDebug?:CommonResponseObjDebug = undefined
}

/**
 * @export 
 * A ApikeyRegenerateV1Response Validation Object
 * @class ValidationObjectApikeyRegenerateV1Response
 */
export class ValidationObjectApikeyRegenerateV1Response {
   mPayload = new ValidationObjectApikeyRegenerateV1ResponseMPayload()
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
} 


