/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.10
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BrandingGetListV1ResponseMPayloadAllOf } from './branding-get-list-v1-response-mpayload-all-of';
import { BrandingListElement } from './branding-list-element';
import { CommonGetListV1ResponseMPayload } from './common-get-list-v1-response-mpayload';

/**
 * @type BrandingGetListV1ResponseMPayload
 * Payload for GET /1/object/branding/getList
 * @export
 */
export type BrandingGetListV1ResponseMPayload = BrandingGetListV1ResponseMPayloadAllOf & CommonGetListV1ResponseMPayload;


