/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomCommunicationListElementResponse } from './custom-communication-list-element-response';

/**
 * Response for GET /1/object/buyercontract/{pkiBuyercontractID}/getCommunicationList
 * @export
 * @interface BuyercontractGetCommunicationListV1ResponseMPayload
 */
export interface BuyercontractGetCommunicationListV1ResponseMPayload {
    /**
     * 
     * @type {Array<CustomCommunicationListElementResponse>}
     * @memberof BuyercontractGetCommunicationListV1ResponseMPayload
     */
    'a_objCommunication': Array<CustomCommunicationListElementResponse>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A BuyercontractGetCommunicationListV1ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectBuyercontractGetCommunicationListV1ResponseMPayload
 */
export class DataObjectBuyercontractGetCommunicationListV1ResponseMPayload {
   a_objCommunication:Array<CustomCommunicationListElementResponse> = []
}

/**
 * @export 
 * A BuyercontractGetCommunicationListV1ResponseMPayload Validation Object
 * @class ValidationObjectBuyercontractGetCommunicationListV1ResponseMPayload
 */
export class ValidationObjectBuyercontractGetCommunicationListV1ResponseMPayload {
   a_objCommunication = {
      type: 'array',
      required: true
   }
} 


