/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonAudit } from './common-audit';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationResponse } from './communication-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationResponseCompoundAllOf } from './communication-response-compound-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationattachmentResponseCompound } from './communicationattachment-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationexternalrecipientResponseCompound } from './communicationexternalrecipient-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationrecipientResponseCompound } from './communicationrecipient-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { ComputedECommunicationDirection } from './computed-ecommunication-direction';
// May contain unused imports in some cases
// @ts-ignore
import { CustomContactNameResponse } from './custom-contact-name-response';
// May contain unused imports in some cases
// @ts-ignore
import { FieldECommunicationImportance } from './field-ecommunication-importance';
// May contain unused imports in some cases
// @ts-ignore
import { FieldECommunicationType } from './field-ecommunication-type';

import { DefaultObject } from '../base'

/**
 * @type CommunicationResponseCompound
 * A Communication Object
 * @export
 */
export type CommunicationResponseCompound = CommunicationResponse & CommunicationResponseCompoundAllOf;


/**
 * @export 
 * A CommunicationResponseCompound Object with automatic temp default value
 * Use this object only for create an empty object to assign a response from server
 * @class DefaultObjectCommunicationResponseCompound
 */
export class DefaultObjectCommunicationResponseCompound extends DefaultObject {
   pkiCommunicationID:number = 0
   eCommunicationImportance:FieldECommunicationImportance = 'High'
   eCommunicationType:FieldECommunicationType = 'Email'
   sCommunicationSubject:string = ''
   eCommunicationDirection:ComputedECommunicationDirection = 'Outbound'
   iCommunicationrecipientCount:number = 0
   objContactFrom:Partial<CustomContactNameResponse> = {}
   objAudit:Partial<CommonAudit> = {}
   a_objCommunicationattachment:Array<CommunicationattachmentResponseCompound> = []
   a_objCommunicationrecipient:Array<CommunicationrecipientResponseCompound> = []
   a_objCommunicationexternalrecipient:Array<CommunicationexternalrecipientResponseCompound> = []
}


