/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommunicationattachmentResponseCompound } from './communicationattachment-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationexternalrecipientResponseCompound } from './communicationexternalrecipient-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { CommunicationrecipientResponseCompound } from './communicationrecipient-response-compound';

import { DefaultObject } from '../base'

/**
 * 
 * @export
 * @interface CommunicationResponseCompoundAllOf
 */
export interface CommunicationResponseCompoundAllOf {
    /**
     * 
     * @type {Array<CommunicationattachmentResponseCompound>}
     * @memberof CommunicationResponseCompoundAllOf
     */
    'a_objCommunicationattachment': Array<CommunicationattachmentResponseCompound>;
    /**
     * 
     * @type {Array<CommunicationrecipientResponseCompound>}
     * @memberof CommunicationResponseCompoundAllOf
     */
    'a_objCommunicationrecipient': Array<CommunicationrecipientResponseCompound>;
    /**
     * 
     * @type {Array<CommunicationexternalrecipientResponseCompound>}
     * @memberof CommunicationResponseCompoundAllOf
     */
    'a_objCommunicationexternalrecipient': Array<CommunicationexternalrecipientResponseCompound>;
}
/**
 * A CommunicationResponseCompoundAllOf Object with automatic temp default value
 * Use this object only for create an empty object to assign a response from server
 * @export 
 * @class DefaultObjectCommunicationResponseCompoundAllOf
 */
export class DefaultObjectCommunicationResponseCompoundAllOf extends DefaultObject {
   a_objCommunicationattachment:Array<CommunicationattachmentResponseCompound> = []
   a_objCommunicationrecipient:Array<CommunicationrecipientResponseCompound> = []
   a_objCommunicationexternalrecipient:Array<CommunicationexternalrecipientResponseCompound> = []
}


