/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactResponse } from './contact-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactinformationsResponseCompound } from './contactinformations-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import type { FieldEContactType } from './field-econtact-type';

/**
 * @type ContactResponseCompound
 * A Contact Object
 * @export
 */
/*export type ContactResponseCompound = ContactResponse;*/
export interface ContactResponseCompound {
}



/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A ContactResponseCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectContactResponseCompound
 */
export class DataObjectContactResponseCompound {
}

/**
 * @export 
 * A ContactResponseCompound Validation Object
 * @class ValidationObjectContactResponseCompound
 */
export class ValidationObjectContactResponseCompound {
} 


