/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CorsResponse } from './cors-response';

/**
 * @type CorsResponseCompound
 * A Cors Object
 * @export
 */
/*export type CorsResponseCompound = CorsResponse;*/
export interface CorsResponseCompound {
}


/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A CorsResponseCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectCorsResponseCompound
 */
export class DataObjectCorsResponseCompound {
}

/**
 * @export 
 * A CorsResponseCompound Validation Object
 * @class ValidationObjectCorsResponseCompound
 */
export class ValidationObjectCorsResponseCompound {
} 


