/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payload for POST /1/object/creditcardmerchant
 * @export
 * @interface CreditcardmerchantCreateObjectV1ResponseMPayload
 */
export interface CreditcardmerchantCreateObjectV1ResponseMPayload {
    /**
     * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     * @type {Array<number>}
     * @memberof CreditcardmerchantCreateObjectV1ResponseMPayload
     */
    /*'a_pkiCreditcardmerchantID': Array<number>;*/
    'a_pkiCreditcardmerchantID': Array<number>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A CreditcardmerchantCreateObjectV1ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectCreditcardmerchantCreateObjectV1ResponseMPayload
 */
export class DataObjectCreditcardmerchantCreateObjectV1ResponseMPayload {
   a_pkiCreditcardmerchantID:Array<number> = []
}

/**
 * @export 
 * A CreditcardmerchantCreateObjectV1ResponseMPayload Validation Object
 * @class ValidationObjectCreditcardmerchantCreateObjectV1ResponseMPayload
 */
export class ValidationObjectCreditcardmerchantCreateObjectV1ResponseMPayload {
   a_pkiCreditcardmerchantID = {
      type: 'array',
      required: true
   }
} 


