/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreditcarddetailResponse } from './creditcarddetail-response';

/**
 * @type CreditcarddetailResponseCompound
 * A Creditcarddetail Object
 * @export
 */
/*export type CreditcarddetailResponseCompound = CreditcarddetailResponse;*/
export interface CreditcarddetailResponseCompound {
    /**
     * The unique ID of the Creditcarddetail
     * @type {number}
     * @memberof CreditcarddetailResponseCompound
     */
    pkiCreditcarddetailID:number 
    /**
     * The unique ID of the Creditcardtype
     * @type {number}
     * @memberof CreditcarddetailResponseCompound
     */
    fkiCreditcardtypeID:number 
    /**
     * The last digits of the Creditcarddetail
     * @type {number}
     * @memberof CreditcarddetailResponseCompound
     */
    iCreditcarddetailLastdigits:number 
    /**
     * The expirationmonth of the Creditcarddetail
     * @type {number}
     * @memberof CreditcarddetailResponseCompound
     */
    iCreditcarddetailExpirationmonth:number 
    /**
     * The expirationyear of the Creditcarddetail
     * @type {number}
     * @memberof CreditcarddetailResponseCompound
     */
    iCreditcarddetailExpirationyear:number 
    /**
     * The civic of the Creditcarddetail
     * @type {string}
     * @memberof CreditcarddetailResponseCompound
     */
    sCreditcarddetailCivic:string 
    /**
     * The street of the Creditcarddetail
     * @type {string}
     * @memberof CreditcarddetailResponseCompound
     */
    sCreditcarddetailStreet:string 
    /**
     * The zip of the Creditcarddetail
     * @type {string}
     * @memberof CreditcarddetailResponseCompound
     */
    sCreditcarddetailZip:string 
}


/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A CreditcarddetailResponseCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectCreditcarddetailResponseCompound
 */
export class DataObjectCreditcarddetailResponseCompound {
    pkiCreditcarddetailID:number = 0
    fkiCreditcardtypeID:number = 0
    iCreditcarddetailLastdigits:number = 0
    iCreditcarddetailExpirationmonth:number = 0
    iCreditcarddetailExpirationyear:number = 0
    sCreditcarddetailCivic:string = ''
    sCreditcarddetailStreet:string = ''
    sCreditcarddetailZip:string = ''
}

/**
 * @export 
 * A CreditcarddetailResponseCompound Validation Object
 * @class ValidationObjectCreditcarddetailResponseCompound
 */
export class ValidationObjectCreditcarddetailResponseCompound {
   pkiCreditcarddetailID = {
      type: 'integer',
      minimum: 0,
      maximum: 65535,
      required: true
   }
   fkiCreditcardtypeID = {
      type: 'integer',
      minimum: 0,
      maximum: 255,
      required: true
   }
   iCreditcarddetailLastdigits = {
      type: 'integer',
      minimum: 0,
      maximum: 9999,
      required: true
   }
   iCreditcarddetailExpirationmonth = {
      type: 'integer',
      minimum: 0,
      maximum: 12,
      required: true
   }
   iCreditcarddetailExpirationyear = {
      type: 'integer',
      minimum: 0,
      maximum: 2200,
      required: true
   }
   sCreditcarddetailCivic = {
      type: 'string',
      pattern: /^[\d]{1,8}$/,
      required: true
   }
   sCreditcarddetailStreet = {
      type: 'string',
      pattern: /^.{1,19}$/,
      required: true
   }
   sCreditcarddetailZip = {
      type: 'string',
      pattern: /^.{0,9}$/,
      required: true
   }
} 


