/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DepartmentAutocompleteElementResponse } from './department-autocomplete-element-response';

/**
 * Payload for POST /2/object/department/getAutocomplete
 * @export
 * @interface DepartmentGetAutocompleteV2ResponseMPayload
 */
export interface DepartmentGetAutocompleteV2ResponseMPayload {
    /**
     * An array of Department autocomplete element response.
     * @type {Array<DepartmentAutocompleteElementResponse>}
     * @memberof DepartmentGetAutocompleteV2ResponseMPayload
     */
    'a_objDepartment': Array<DepartmentAutocompleteElementResponse>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A DepartmentGetAutocompleteV2ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectDepartmentGetAutocompleteV2ResponseMPayload
 */
export class DataObjectDepartmentGetAutocompleteV2ResponseMPayload {
   a_objDepartment:Array<DepartmentAutocompleteElementResponse> = []
}

/**
 * @export 
 * A DepartmentGetAutocompleteV2ResponseMPayload Validation Object
 * @class ValidationObjectDepartmentGetAutocompleteV2ResponseMPayload
 */
export class ValidationObjectDepartmentGetAutocompleteV2ResponseMPayload {
   a_objDepartment = {
      type: 'array',
      required: true
   }
} 


