/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomDiscussionconfigurationResponse } from './custom-discussionconfiguration-response';

/**
 * A Discussion Object
 * @export
 * @interface DiscussionResponse
 */
export interface DiscussionResponse {
    /**
     * The unique ID of the Discussion
     * @type {number}
     * @memberof DiscussionResponse
     */
    /*'pkiDiscussionID': number;*/
    'pkiDiscussionID': number;
    /**
     * The description of the Discussion
     * @type {string}
     * @memberof DiscussionResponse
     */
    /*'sDiscussionDescription': string;*/
    'sDiscussionDescription': string;
    /**
     * Whether if it\'s an closed
     * @type {boolean}
     * @memberof DiscussionResponse
     */
    /*'bDiscussionClosed': boolean;*/
    'bDiscussionClosed': boolean;
    /**
     * The date the Discussion was last read
     * @type {string}
     * @memberof DiscussionResponse
     */
    /*'dtDiscussionLastread'?: string;*/
    'dtDiscussionLastread'?: string;
    /**
     * The count of Attachment.
     * @type {number}
     * @memberof DiscussionResponse
     */
    /*'iDiscussionmessageCount': number;*/
    'iDiscussionmessageCount': number;
    /**
     * The count of Attachment.
     * @type {number}
     * @memberof DiscussionResponse
     */
    /*'iDiscussionmessageCountunread': number;*/
    'iDiscussionmessageCountunread': number;
    /**
     * 
     * @type {CustomDiscussionconfigurationResponse}
     * @memberof DiscussionResponse
     */
    /*'objDiscussionconfiguration'?: CustomDiscussionconfigurationResponse;*/
    'objDiscussionconfiguration'?: CustomDiscussionconfigurationResponse;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCustomDiscussionconfigurationResponse } from './'
// @ts-ignore
import { ValidationObjectCustomDiscussionconfigurationResponse } from './'

/**
 * @export 
 * A DiscussionResponse Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectDiscussionResponse
 */
export class DataObjectDiscussionResponse {
   pkiDiscussionID:number = 0
   sDiscussionDescription:string = ''
   bDiscussionClosed:boolean = false
   dtDiscussionLastread?:string = undefined
   iDiscussionmessageCount:number = 0
   iDiscussionmessageCountunread:number = 0
   objDiscussionconfiguration?:CustomDiscussionconfigurationResponse = undefined
}

/**
 * @export 
 * A DiscussionResponse Validation Object
 * @class ValidationObjectDiscussionResponse
 */
export class ValidationObjectDiscussionResponse {
   pkiDiscussionID = {
      type: 'integer',
      minimum: 0,
      maximum: 16777215,
      required: true
   }
   sDiscussionDescription = {
      type: 'string',
      pattern: /^.{0,75}$/,
      required: true
   }
   bDiscussionClosed = {
      type: 'boolean',
      required: true
   }
   dtDiscussionLastread = {
      type: 'string',
      required: false
   }
   iDiscussionmessageCount = {
      type: 'integer',
      required: true
   }
   iDiscussionmessageCountunread = {
      type: 'integer',
      required: true
   }
   objDiscussionconfiguration = new ValidationObjectCustomDiscussionconfigurationResponse()
} 


