/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { DiscussionmessageCreateObjectV1ResponseMPayload } from './discussionmessage-create-object-v1-response-mpayload';

/**
 * @type DiscussionmessageCreateObjectV1Response
 * Response for POST /1/object/discussionmessage
 * @export
 */
/*export type DiscussionmessageCreateObjectV1Response = CommonResponse;*/
export interface DiscussionmessageCreateObjectV1Response {
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof DiscussionmessageCreateObjectV1Response
     */
    objDebugPayload:CommonResponseObjDebugPayload 
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof DiscussionmessageCreateObjectV1Response
     */
    objDebug?:CommonResponseObjDebug 
    /**
     * 
     * @type {DiscussionmessageCreateObjectV1ResponseMPayload}
     * @memberof DiscussionmessageCreateObjectV1Response
     */
    mPayload:DiscussionmessageCreateObjectV1ResponseMPayload 
}


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { DataObjectDiscussionmessageCreateObjectV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectDiscussionmessageCreateObjectV1ResponseMPayload } from './'

/**
 * @export 
 * A DiscussionmessageCreateObjectV1Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectDiscussionmessageCreateObjectV1Response
 */
export class DataObjectDiscussionmessageCreateObjectV1Response {
    objDebugPayload:CommonResponseObjDebugPayload = new DataObjectCommonResponseObjDebugPayload()
    objDebug?:CommonResponseObjDebug = undefined
    mPayload:DiscussionmessageCreateObjectV1ResponseMPayload = new DataObjectDiscussionmessageCreateObjectV1ResponseMPayload()
}

/**
 * @export 
 * A DiscussionmessageCreateObjectV1Response Validation Object
 * @class ValidationObjectDiscussionmessageCreateObjectV1Response
 */
export class ValidationObjectDiscussionmessageCreateObjectV1Response {
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
   mPayload = new ValidationObjectDiscussionmessageCreateObjectV1ResponseMPayload()
} 


