/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomAttachmentImportIntoEDMRequest } from './custom-attachment-import-into-edmrequest';

/**
 * Request for POST /1/object/employee/{pkiEmployeeID}/importIntoEDM
 */
export interface EmployeeImportIntoEDMV1Request {
    /*'a_objAttachment': Array<CustomAttachmentImportIntoEDMRequest>;*/
    'a_objAttachment': Array<CustomAttachmentImportIntoEDMRequest>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EmployeeImportIntoEDMV1Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEmployeeImportIntoEDMV1Request
 */
export class DataObjectEmployeeImportIntoEDMV1Request {
   a_objAttachment:Array<CustomAttachmentImportIntoEDMRequest> = []
}

/**
 * @export 
 * A EmployeeImportIntoEDMV1Request Validation Object
 * @class ValidationObjectEmployeeImportIntoEDMV1Request
 */
export class ValidationObjectEmployeeImportIntoEDMV1Request {
   a_objAttachment = {
      type: 'array',
      required: true
   }
} 


