/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request for POST /1/object/externalbroker/{pkiExternalbrokerID}/batchDownload
 */
export interface ExternalbrokerBatchDownloadV1Request {
    /*'a_pkiAttachmentID': Array<number>;*/
    'a_pkiAttachmentID': Array<number>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A ExternalbrokerBatchDownloadV1Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectExternalbrokerBatchDownloadV1Request
 */
export class DataObjectExternalbrokerBatchDownloadV1Request {
   a_pkiAttachmentID:Array<number> = []
}

/**
 * @export 
 * A ExternalbrokerBatchDownloadV1Request Validation Object
 * @class ValidationObjectExternalbrokerBatchDownloadV1Request
 */
export class ValidationObjectExternalbrokerBatchDownloadV1Request {
   a_pkiAttachmentID = {
      type: 'array',
      minItems: 1,
      required: true
   }
} 


