/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzdoctemplatedocumentRequestPatch } from './ezdoctemplatedocument-request-patch';

/**
 * Request for PATCH /1/object/ezdoctemplatedocument/{pkiEzdoctemplatedocumentID}
 * @export
 * @interface EzdoctemplatedocumentPatchObjectV1Request
 */
export interface EzdoctemplatedocumentPatchObjectV1Request {
    /**
     * 
     * @type {EzdoctemplatedocumentRequestPatch}
     * @memberof EzdoctemplatedocumentPatchObjectV1Request
     */
    /*'objEzdoctemplatedocument': EzdoctemplatedocumentRequestPatch;*/
    'objEzdoctemplatedocument': EzdoctemplatedocumentRequestPatch;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzdoctemplatedocumentRequestPatch } from './'
// @ts-ignore
import { ValidationObjectEzdoctemplatedocumentRequestPatch } from './'

/**
 * @export 
 * A EzdoctemplatedocumentPatchObjectV1Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzdoctemplatedocumentPatchObjectV1Request
 */
export class DataObjectEzdoctemplatedocumentPatchObjectV1Request {
   objEzdoctemplatedocument:EzdoctemplatedocumentRequestPatch = new DataObjectEzdoctemplatedocumentRequestPatch()
}

/**
 * @export 
 * A EzdoctemplatedocumentPatchObjectV1Request Validation Object
 * @class ValidationObjectEzdoctemplatedocumentPatchObjectV1Request
 */
export class ValidationObjectEzdoctemplatedocumentPatchObjectV1Request {
   objEzdoctemplatedocument = new ValidationObjectEzdoctemplatedocumentRequestPatch()
} 


