/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldEEzmaxinvoicingagentVariationezmax } from './field-eezmaxinvoicingagent-variationezmax';
// May contain unused imports in some cases
// @ts-ignore
import type { FieldEEzmaxinvoicingagentVariationezsign } from './field-eezmaxinvoicingagent-variationezsign';

/**
 * A Ezmaxinvoicingagent Object
 * @export
 * @interface EzmaxinvoicingagentResponse
 */
export interface EzmaxinvoicingagentResponse {
    /**
     * The unique ID of the Ezmaxinvoicingagent
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'pkiEzmaxinvoicingagentID'?: number;*/
    'pkiEzmaxinvoicingagentID'?: number;
    /**
     * The unique ID of the Ezmaxinvoicing
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'fkiEzmaxinvoicingID'?: number;*/
    'fkiEzmaxinvoicingID'?: number;
    /**
     * The unique ID of the Billingentityinternal.
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'fkiBillingentityinternalID': number;*/
    'fkiBillingentityinternalID': number;
    /**
     * The description of the Billingentityinternal in the language of the requester
     * @type {string}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'sBillingentityinternalDescriptionX': string;*/
    'sBillingentityinternalDescriptionX': string;
    /**
     * The unique ID of the Agent.
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'fkiAgentID'?: number;*/
    'fkiAgentID'?: number;
    /**
     * The unique ID of the Broker.
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'fkiBrokerID'?: number;*/
    'fkiBrokerID'?: number;
    /**
     * The number of sessions
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentSession': number;*/
    'iEzmaxinvoicingagentSession': number;
    /**
     * The number of times this user was cloned
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentCloned': number;*/
    'iEzmaxinvoicingagentCloned': number;
    /**
     * The number of invoices
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentInvoice': number;*/
    'iEzmaxinvoicingagentInvoice': number;
    /**
     * The number of inscriptions
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentInscription': number;*/
    'iEzmaxinvoicingagentInscription': number;
    /**
     * The number of active inscriptions
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentInscriptionactive': number;*/
    'iEzmaxinvoicingagentInscriptionactive': number;
    /**
     * The number of sales
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentSale': number;*/
    'iEzmaxinvoicingagentSale': number;
    /**
     * The number of otherincomes
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentOtherincome': number;*/
    'iEzmaxinvoicingagentOtherincome': number;
    /**
     * The number of commission calculations
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentCommissioncalculation': number;*/
    'iEzmaxinvoicingagentCommissioncalculation': number;
    /**
     * The number of ezsign documents
     * @type {number}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'iEzmaxinvoicingagentEzsigndocument': number;*/
    'iEzmaxinvoicingagentEzsigndocument': number;
    /**
     * Whether the agent has an eZsign account
     * @type {boolean}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'bEzmaxinvoicingagentEzsignaccount': boolean;*/
    'bEzmaxinvoicingagentEzsignaccount': boolean;
    /**
     * Whether it is billable for eZmax
     * @type {boolean}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'bEzmaxinvoicingagentBillableezmax': boolean;*/
    'bEzmaxinvoicingagentBillableezmax': boolean;
    /**
     * 
     * @type {FieldEEzmaxinvoicingagentVariationezmax}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'eEzmaxinvoicingagentVariationezmax': FieldEEzmaxinvoicingagentVariationezmax;*/
    'eEzmaxinvoicingagentVariationezmax': FieldEEzmaxinvoicingagentVariationezmax;
    /**
     * Whether it is billable for eZsign
     * @type {boolean}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'bEzmaxinvoicingagentBillableezsign': boolean;*/
    'bEzmaxinvoicingagentBillableezsign': boolean;
    /**
     * 
     * @type {FieldEEzmaxinvoicingagentVariationezsign}
     * @memberof EzmaxinvoicingagentResponse
     */
    /*'eEzmaxinvoicingagentVariationezsign': FieldEEzmaxinvoicingagentVariationezsign;*/
    'eEzmaxinvoicingagentVariationezsign': FieldEEzmaxinvoicingagentVariationezsign;
}


/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzmaxinvoicingagentResponse Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzmaxinvoicingagentResponse
 */
export class DataObjectEzmaxinvoicingagentResponse {
   pkiEzmaxinvoicingagentID?:number = undefined
   fkiEzmaxinvoicingID?:number = undefined
   fkiBillingentityinternalID:number = 0
   sBillingentityinternalDescriptionX:string = ''
   fkiAgentID?:number = undefined
   fkiBrokerID?:number = undefined
   iEzmaxinvoicingagentSession:number = 0
   iEzmaxinvoicingagentCloned:number = 0
   iEzmaxinvoicingagentInvoice:number = 0
   iEzmaxinvoicingagentInscription:number = 0
   iEzmaxinvoicingagentInscriptionactive:number = 0
   iEzmaxinvoicingagentSale:number = 0
   iEzmaxinvoicingagentOtherincome:number = 0
   iEzmaxinvoicingagentCommissioncalculation:number = 0
   iEzmaxinvoicingagentEzsigndocument:number = 0
   bEzmaxinvoicingagentEzsignaccount:boolean = false
   bEzmaxinvoicingagentBillableezmax:boolean = false
   eEzmaxinvoicingagentVariationezmax:FieldEEzmaxinvoicingagentVariationezmax = 'Charge'
   bEzmaxinvoicingagentBillableezsign:boolean = false
   eEzmaxinvoicingagentVariationezsign:FieldEEzmaxinvoicingagentVariationezsign = 'Charge'
}

/**
 * @export 
 * A EzmaxinvoicingagentResponse Validation Object
 * @class ValidationObjectEzmaxinvoicingagentResponse
 */
export class ValidationObjectEzmaxinvoicingagentResponse {
   pkiEzmaxinvoicingagentID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   fkiEzmaxinvoicingID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   fkiBillingentityinternalID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   sBillingentityinternalDescriptionX = {
      type: 'string',
      required: true
   }
   fkiAgentID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   fkiBrokerID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   iEzmaxinvoicingagentSession = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentCloned = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentInvoice = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentInscription = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentInscriptionactive = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentSale = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentOtherincome = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentCommissioncalculation = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzmaxinvoicingagentEzsigndocument = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   bEzmaxinvoicingagentEzsignaccount = {
      type: 'boolean',
      required: true
   }
   bEzmaxinvoicingagentBillableezmax = {
      type: 'boolean',
      required: true
   }
   eEzmaxinvoicingagentVariationezmax = {
      type: 'enum',
      allowableValues: ['Charge','Refund','Same'],
      required: true
   }
   bEzmaxinvoicingagentBillableezsign = {
      type: 'boolean',
      required: true
   }
   eEzmaxinvoicingagentVariationezsign = {
      type: 'enum',
      allowableValues: ['Charge','Refund','Same'],
      required: true
   }
} 


