/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EnumHorizontalalignment } from './enum-horizontalalignment';
// May contain unused imports in some cases
// @ts-ignore
import { EnumVerticalalignment } from './enum-verticalalignment';
// May contain unused imports in some cases
// @ts-ignore
import { EzsignannotationResponse } from './ezsignannotation-response';
// May contain unused imports in some cases
// @ts-ignore
import { FieldEEzsignannotationType } from './field-eezsignannotation-type';
// May contain unused imports in some cases
// @ts-ignore
import { TextstylestaticResponseCompound } from './textstylestatic-response-compound';

/**
 * @type EzsignannotationResponseCompound
 * A Ezsignannotation Object
 * @export
 */
export type EzsignannotationResponseCompound = EzsignannotationResponse;



/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectTextstylestaticResponseCompound } from './'
// @ts-ignore
import { ValidationObjectTextstylestaticResponseCompound } from './'

/**
 * @export 
 * A EzsignannotationResponseCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignannotationResponseCompound
 */
export class DataObjectEzsignannotationResponseCompound {
    pkiEzsignannotationID:number = 0
    fkiEzsigndocumentID:number = 0
    eEzsignannotationHorizontalalignment?:EnumHorizontalalignment = undefined
    eEzsignannotationVerticalalignment?:EnumVerticalalignment = undefined
    eEzsignannotationType:FieldEEzsignannotationType = 'StrikethroughBlock'
    iEzsignannotationX:number = 0
    iEzsignannotationY:number = 0
    iEzsignannotationWidth?:number = undefined
    iEzsignannotationHeight?:number = undefined
    sEzsignannotationText?:string = undefined
    iEzsignpagePagenumber:number = 0
    objTextstylestatic?:TextstylestaticResponseCompound = undefined
}

/**
 * @export 
 * A EzsignannotationResponseCompound Validation Object
 * @class ValidationObjectEzsignannotationResponseCompound
 */
export class ValidationObjectEzsignannotationResponseCompound {
   pkiEzsignannotationID = {
      type: 'integer',
      required: true
   }
   fkiEzsigndocumentID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   eEzsignannotationHorizontalalignment = {
      type: 'enum',
      allowableValues: ['Center','Left','Right'],
      required: false
   }
   eEzsignannotationVerticalalignment = {
      type: 'enum',
      allowableValues: ['Bottom','Middle','Top'],
      required: false
   }
   eEzsignannotationType = {
      type: 'enum',
      allowableValues: ['StrikethroughBlock','StrikethroughLine','Text'],
      required: true
   }
   iEzsignannotationX = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzsignannotationY = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzsignannotationWidth = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   iEzsignannotationHeight = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   sEzsignannotationText = {
      type: 'string',
      required: false
   }
   iEzsignpagePagenumber = {
      type: 'integer',
      minimum: 1,
      required: true
   }
   objTextstylestatic = new ValidationObjectTextstylestaticResponseCompound()
} 


