/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonAudit } from './common-audit';
// May contain unused imports in some cases
// @ts-ignore
import { EzsigntemplateResponseCompound } from './ezsigntemplate-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { EzsigntemplatedocumentResponse } from './ezsigntemplatedocument-response';
// May contain unused imports in some cases
// @ts-ignore
import { EzsigntemplatesignerResponseCompound } from './ezsigntemplatesigner-response-compound';

/**
 * @type EzsigntemplateGetObjectV1ResponseMPayload
 * Payload for GET /1/object/ezsigntemplate/{pkiEzsigntemplateID}
 * @export
 */
export type EzsigntemplateGetObjectV1ResponseMPayload = EzsigntemplateResponseCompound;


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonAudit } from './'
// @ts-ignore
import { DataObjectEzsigntemplatedocumentResponse } from './'
// @ts-ignore
import { ValidationObjectCommonAudit } from './'
// @ts-ignore
import { ValidationObjectEzsigntemplatedocumentResponse } from './'

/**
 * @export 
 * A EzsigntemplateGetObjectV1ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsigntemplateGetObjectV1ResponseMPayload
 */
export class DataObjectEzsigntemplateGetObjectV1ResponseMPayload {
   pkiEzsigntemplateID:number = 0
   fkiEzsigntemplatedocumentID?:number = undefined
   fkiEzsignfoldertypeID:number = 0
   fkiLanguageID:number = 0
   sLanguageNameX:string = ''
   sEzsigntemplateDescription:string = ''
   bEzsigntemplateAdminonly:boolean = false
   sEzsignfoldertypeNameX:string = ''
   objAudit:CommonAudit = new DataObjectCommonAudit()
   objEzsigntemplatedocument?:EzsigntemplatedocumentResponse = undefined
   a_objEzsigntemplatesigner:Array<EzsigntemplatesignerResponseCompound> = []
}

/**
 * @export 
 * A EzsigntemplateGetObjectV1ResponseMPayload Validation Object
 * @class ValidationObjectEzsigntemplateGetObjectV1ResponseMPayload
 */
export class ValidationObjectEzsigntemplateGetObjectV1ResponseMPayload {
   pkiEzsigntemplateID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiEzsigntemplatedocumentID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   fkiEzsignfoldertypeID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiLanguageID = {
      type: 'integer',
      minimum: 1,
      maximum: 2,
      required: true
   }
   sLanguageNameX = {
      type: 'string',
      required: true
   }
   sEzsigntemplateDescription = {
      type: 'string',
      required: true
   }
   bEzsigntemplateAdminonly = {
      type: 'boolean',
      required: true
   }
   sEzsignfoldertypeNameX = {
      type: 'string',
      required: true
   }
   objAudit = new ValidationObjectCommonAudit()
   objEzsigntemplatedocument = new ValidationObjectEzsigntemplatedocumentResponse()
   a_objEzsigntemplatesigner = {
      type: 'array',
      required: true
   }
} 


