/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Payload for POST /3/object/ezsignfolder
 * @export
 * @interface EzsignfolderCreateObjectV3ResponseMPayload
 */
export interface EzsignfolderCreateObjectV3ResponseMPayload {
    /**
     * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     * @type {Array<number>}
     * @memberof EzsignfolderCreateObjectV3ResponseMPayload
     */
    /*'a_pkiEzsignfolderID': Array<number>;*/
    'a_pkiEzsignfolderID': Array<number>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsignfolderCreateObjectV3ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignfolderCreateObjectV3ResponseMPayload
 */
export class DataObjectEzsignfolderCreateObjectV3ResponseMPayload {
   a_pkiEzsignfolderID:Array<number> = []
}

/**
 * @export 
 * A EzsignfolderCreateObjectV3ResponseMPayload Validation Object
 * @class ValidationObjectEzsignfolderCreateObjectV3ResponseMPayload
 */
export class ValidationObjectEzsignfolderCreateObjectV3ResponseMPayload {
   a_pkiEzsignfolderID = {
      type: 'array',
      minItems: 1,
      required: true
   }
} 


