/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A Ezsigntemplatepackagesignermembership Object
 * @export
 * @interface EzsigntemplatepackagesignermembershipResponse
 */
export interface EzsigntemplatepackagesignermembershipResponse {
    /**
     * The unique ID of the Ezsigntemplatepackagesignermembership
     * @type {number}
     * @memberof EzsigntemplatepackagesignermembershipResponse
     */
    /*'pkiEzsigntemplatepackagesignermembershipID': number;*/
    'pkiEzsigntemplatepackagesignermembershipID': number;
    /**
     * The unique ID of the Ezsigntemplatepackagemembership
     * @type {number}
     * @memberof EzsigntemplatepackagesignermembershipResponse
     */
    /*'fkiEzsigntemplatepackagemembershipID': number;*/
    'fkiEzsigntemplatepackagemembershipID': number;
    /**
     * The unique ID of the Ezsigntemplatepackagesigner
     * @type {number}
     * @memberof EzsigntemplatepackagesignermembershipResponse
     */
    /*'fkiEzsigntemplatepackagesignerID': number;*/
    'fkiEzsigntemplatepackagesignerID': number;
    /**
     * The unique ID of the Ezsigntemplatesigner
     * @type {number}
     * @memberof EzsigntemplatepackagesignermembershipResponse
     */
    /*'fkiEzsigntemplatesignerID': number;*/
    'fkiEzsigntemplatesignerID': number;
    /**
     * The Copy number in case of multiple copies.
     * @type {number}
     * @memberof EzsigntemplatepackagesignermembershipResponse
     */
    /*'iEzsigntemplatepackagesignermembershipCopy'?: number;*/
    'iEzsigntemplatepackagesignermembershipCopy'?: number;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsigntemplatepackagesignermembershipResponse Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsigntemplatepackagesignermembershipResponse
 */
export class DataObjectEzsigntemplatepackagesignermembershipResponse {
   pkiEzsigntemplatepackagesignermembershipID:number = 0
   fkiEzsigntemplatepackagemembershipID:number = 0
   fkiEzsigntemplatepackagesignerID:number = 0
   fkiEzsigntemplatesignerID:number = 0
   iEzsigntemplatepackagesignermembershipCopy?:number = undefined
}

/**
 * @export 
 * A EzsigntemplatepackagesignermembershipResponse Validation Object
 * @class ValidationObjectEzsigntemplatepackagesignermembershipResponse
 */
export class ValidationObjectEzsigntemplatepackagesignermembershipResponse {
   pkiEzsigntemplatepackagesignermembershipID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiEzsigntemplatepackagemembershipID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiEzsigntemplatepackagesignerID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiEzsigntemplatesignerID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   iEzsigntemplatepackagesignermembershipCopy = {
      type: 'integer',
      minimum: 1,
      required: false
   }
} 


