/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EzsignbulksendtransmissionResponse } from './ezsignbulksendtransmission-response';

/**
 * Payload for POST /2/object/ezsignbulksend/{pkiEzsignbulksendID}/createEzsignbulksendtransmission
 * @export
 * @interface EzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload
 */
export interface EzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload {
    /**
     * 
     * @type {EzsignbulksendtransmissionResponse}
     * @memberof EzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload
     */
    /*'objEzsignbulksendtransmission': EzsignbulksendtransmissionResponse;*/
    'objEzsignbulksendtransmission': EzsignbulksendtransmissionResponse;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzsignbulksendtransmissionResponse } from './'
// @ts-ignore
import { ValidationObjectEzsignbulksendtransmissionResponse } from './'

/**
 * @export 
 * A EzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload
 */
export class DataObjectEzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload {
   objEzsignbulksendtransmission:EzsignbulksendtransmissionResponse = new DataObjectEzsignbulksendtransmissionResponse()
}

/**
 * @export 
 * A EzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload Validation Object
 * @class ValidationObjectEzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload
 */
export class ValidationObjectEzsignbulksendCreateEzsignbulksendtransmissionV2ResponseMPayload {
   objEzsignbulksendtransmission = new ValidationObjectEzsignbulksendtransmissionResponse()
} 


