/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsignbulksendsignermappingRequest } from './ezsignbulksendsignermapping-request';

/**
 * @type EzsignbulksendsignermappingRequestCompound
 * A Ezsignbulksendsignermapping Object and children
 * @export
 */
export type EzsignbulksendsignermappingRequestCompound = EzsignbulksendsignermappingRequest;


/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsignbulksendsignermappingRequestCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignbulksendsignermappingRequestCompound
 */
export class DataObjectEzsignbulksendsignermappingRequestCompound {
    pkiEzsignbulksendsignermappingID?:number = undefined
    fkiEzsignbulksendID:number = 0
    fkiUserID?:number = undefined
    sEzsignbulksendsignermappingDescription:string = ''
}

/**
 * @export 
 * A EzsignbulksendsignermappingRequestCompound Validation Object
 * @class ValidationObjectEzsignbulksendsignermappingRequestCompound
 */
export class ValidationObjectEzsignbulksendsignermappingRequestCompound {
   pkiEzsignbulksendsignermappingID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   fkiEzsignbulksendID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiUserID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   sEzsignbulksendsignermappingDescription = {
      type: 'string',
      required: true
   }
} 


