/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomFormsDataFolderResponse } from './custom-forms-data-folder-response';

/**
 * Payload for GET/1/object/ezsigntemplatepublic/{pkiEzsigntemplatepublicID}/getFormsData
 * @export
 * @interface EzsigntemplatepublicGetFormsDataV1ResponseMPayload
 */
export interface EzsigntemplatepublicGetFormsDataV1ResponseMPayload {
    /**
     * 
     * @type {Array<CustomFormsDataFolderResponse>}
     * @memberof EzsigntemplatepublicGetFormsDataV1ResponseMPayload
     */
    /*'a_objFormsDataFolder': Array<CustomFormsDataFolderResponse>;*/
    'a_objFormsDataFolder': Array<CustomFormsDataFolderResponse>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsigntemplatepublicGetFormsDataV1ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsigntemplatepublicGetFormsDataV1ResponseMPayload
 */
export class DataObjectEzsigntemplatepublicGetFormsDataV1ResponseMPayload {
   a_objFormsDataFolder:Array<CustomFormsDataFolderResponse> = []
}

/**
 * @export 
 * A EzsigntemplatepublicGetFormsDataV1ResponseMPayload Validation Object
 * @class ValidationObjectEzsigntemplatepublicGetFormsDataV1ResponseMPayload
 */
export class ValidationObjectEzsigntemplatepublicGetFormsDataV1ResponseMPayload {
   a_objFormsDataFolder = {
      type: 'array',
      required: true
   }
} 


