/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsigndocumentRequestCompound } from './ezsigndocument-request-compound';

/**
 * Request for POST /2/object/ezsigndocument
 * @export
 * @interface EzsigndocumentCreateObjectV2Request
 */
export interface EzsigndocumentCreateObjectV2Request {
    /**
     * 
     * @type {Array<EzsigndocumentRequestCompound>}
     * @memberof EzsigndocumentCreateObjectV2Request
     */
    'a_objEzsigndocument': Array<EzsigndocumentRequestCompound>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsigndocumentCreateObjectV2Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsigndocumentCreateObjectV2Request
 */
export class DataObjectEzsigndocumentCreateObjectV2Request {
   a_objEzsigndocument:Array<EzsigndocumentRequestCompound> = []
}

/**
 * @export 
 * A EzsigndocumentCreateObjectV2Request Validation Object
 * @class ValidationObjectEzsigndocumentCreateObjectV2Request
 */
export class ValidationObjectEzsigndocumentCreateObjectV2Request {
   a_objEzsigndocument = {
      type: 'array',
      minItems: 1,
      required: true
   }
} 


