/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonResponse } from './common-response';
import { CommonResponseObjDebug } from './common-response-obj-debug';
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
import { EzsigndocumentCreateObjectV1ResponseAllOf } from './ezsigndocument-create-object-v1-response-all-of';
import { EzsigndocumentCreateObjectV1ResponseMPayload } from './ezsigndocument-create-object-v1-response-mpayload';

/**
 * @type EzsigndocumentCreateObjectV1Response
 * Response for POST /1/object/ezsigndocument
 * @export
 */
export type EzsigndocumentCreateObjectV1Response = CommonResponse & EzsigndocumentCreateObjectV1ResponseAllOf;


