/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsignSuggestSignersV1ResponseMPayload } from './ezsign-suggest-signers-v1-response-mpayload';

/**
 * 
 * @export
 * @interface EzsignSuggestSignersV1ResponseAllOf
 */
export interface EzsignSuggestSignersV1ResponseAllOf {
    /**
     * 
     * @type {EzsignSuggestSignersV1ResponseMPayload}
     * @memberof EzsignSuggestSignersV1ResponseAllOf
     */
    'mPayload': EzsignSuggestSignersV1ResponseMPayload;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzsignSuggestSignersV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectEzsignSuggestSignersV1ResponseMPayload } from './'

/**
 * @export 
 * A EzsignSuggestSignersV1ResponseAllOf Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignSuggestSignersV1ResponseAllOf
 */
export class DataObjectEzsignSuggestSignersV1ResponseAllOf {
   mPayload:EzsignSuggestSignersV1ResponseMPayload = new DataObjectEzsignSuggestSignersV1ResponseMPayload()
}

/**
 * @export 
 * A EzsignSuggestSignersV1ResponseAllOf Validation Object
 * @class ValidationObjectEzsignSuggestSignersV1ResponseAllOf
 */
export class ValidationObjectEzsignSuggestSignersV1ResponseAllOf {
   mPayload = new ValidationObjectEzsignSuggestSignersV1ResponseMPayload()
} 


