/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.10
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request for POST /1/object/ezsignbulksend/{pkiEzsignbulksendID}/reorder
 * @export
 * @interface EzsignbulksendReorderV1Request
 */
export interface EzsignbulksendReorderV1Request {
    /**
     * 
     * @type {Array<number>}
     * @memberof EzsignbulksendReorderV1Request
     */
    'a_pkiEzsignbulksenddocumentmappingID': Array<number>;
}

