/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EzsignfolderGetListV1ResponseMPayload } from './ezsignfolder-get-list-v1-response-mpayload';

/**
 * 
 * @export
 * @interface EzsignfolderGetListV1ResponseAllOf
 */
export interface EzsignfolderGetListV1ResponseAllOf {
    /**
     * 
     * @type {EzsignfolderGetListV1ResponseMPayload}
     * @memberof EzsignfolderGetListV1ResponseAllOf
     */
    'mPayload': EzsignfolderGetListV1ResponseMPayload;
}

