/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload } from './ezsignfolder-get-ezsignfoldersignerassociations-v1-response-mpayload';

/**
 * 
 * @export
 * @interface EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf
 */
export interface EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf {
    /**
     * 
     * @type {EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload}
     * @memberof EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf
     */
    'mPayload': EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload } from './'

/**
 * @export 
 * A EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf
 */
export class DataObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf {
   mPayload:EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload = new DataObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload()
}

/**
 * @export 
 * A EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf Validation Object
 * @class ValidationObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf
 */
export class ValidationObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf {
   mPayload = new ValidationObjectEzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload()
} 


