/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsignformfieldgroupGetObjectV2ResponseMPayload } from './ezsignformfieldgroup-get-object-v2-response-mpayload';

/**
 * 
 * @export
 * @interface EzsignformfieldgroupGetObjectV2ResponseAllOf
 */
export interface EzsignformfieldgroupGetObjectV2ResponseAllOf {
    /**
     * 
     * @type {EzsignformfieldgroupGetObjectV2ResponseMPayload}
     * @memberof EzsignformfieldgroupGetObjectV2ResponseAllOf
     */
    'mPayload': EzsignformfieldgroupGetObjectV2ResponseMPayload;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzsignformfieldgroupGetObjectV2ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectEzsignformfieldgroupGetObjectV2ResponseMPayload } from './'

/**
 * @export 
 * A EzsignformfieldgroupGetObjectV2ResponseAllOf Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignformfieldgroupGetObjectV2ResponseAllOf
 */
export class DataObjectEzsignformfieldgroupGetObjectV2ResponseAllOf {
   mPayload:EzsignformfieldgroupGetObjectV2ResponseMPayload = new DataObjectEzsignformfieldgroupGetObjectV2ResponseMPayload()
}

/**
 * @export 
 * A EzsignformfieldgroupGetObjectV2ResponseAllOf Validation Object
 * @class ValidationObjectEzsignformfieldgroupGetObjectV2ResponseAllOf
 */
export class ValidationObjectEzsignformfieldgroupGetObjectV2ResponseAllOf {
   mPayload = new ValidationObjectEzsignformfieldgroupGetObjectV2ResponseMPayload()
} 


