/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { EzsignfolderGetActionableElementsV3ResponseMPayload } from './ezsignfolder-get-actionable-elements-v3-response-mpayload';

/**
 * @type EzsignfolderGetActionableElementsV3Response
 * Response for GET /3/object/ezsignfolder/{pkiEzsignfolderID}/getActionableElements
 */
/*export type EzsignfolderGetActionableElementsV3Response = CommonResponse;*/
export interface EzsignfolderGetActionableElementsV3Response {
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof EzsignfolderGetActionableElementsV3Response
     */
    objDebugPayload:CommonResponseObjDebugPayload 
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof EzsignfolderGetActionableElementsV3Response
     */
    objDebug?:CommonResponseObjDebug 
    /**
     * 
     * @type {EzsignfolderGetActionableElementsV3ResponseMPayload}
     * @memberof EzsignfolderGetActionableElementsV3Response
     */
    mPayload:EzsignfolderGetActionableElementsV3ResponseMPayload 
}


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { DataObjectEzsignfolderGetActionableElementsV3ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectEzsignfolderGetActionableElementsV3ResponseMPayload } from './'

/**
 * @export 
 * A EzsignfolderGetActionableElementsV3Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignfolderGetActionableElementsV3Response
 */
export class DataObjectEzsignfolderGetActionableElementsV3Response {
    objDebugPayload:CommonResponseObjDebugPayload = new DataObjectCommonResponseObjDebugPayload()
    objDebug?:CommonResponseObjDebug = undefined
    mPayload:EzsignfolderGetActionableElementsV3ResponseMPayload = new DataObjectEzsignfolderGetActionableElementsV3ResponseMPayload()
}

/**
 * @export 
 * A EzsignfolderGetActionableElementsV3Response Validation Object
 * @class ValidationObjectEzsignfolderGetActionableElementsV3Response
 */
export class ValidationObjectEzsignfolderGetActionableElementsV3Response {
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
   mPayload = new ValidationObjectEzsignfolderGetActionableElementsV3ResponseMPayload()
} 


