/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonResponse } from './common-response';
import { CommonResponseObjDebug } from './common-response-obj-debug';
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
import { EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf } from './ezsignfolder-get-ezsignfoldersignerassociations-v1-response-all-of';
import { EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload } from './ezsignfolder-get-ezsignfoldersignerassociations-v1-response-mpayload';

/**
 * @type EzsignfolderGetEzsignfoldersignerassociationsV1Response
 * Response for the /1/object/ezsignfolder/{pkiEzsignfolder}/getEzsignfoldersignerassociations API Request
 * @export
 */
export type EzsignfolderGetEzsignfoldersignerassociationsV1Response = CommonResponse & EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf;


