/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonResponse } from './common-response';
import { CommonResponseObjDebug } from './common-response-obj-debug';
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
import { EzsigndocumentGetObjectV1ResponseAllOf } from './ezsigndocument-get-object-v1-response-all-of';
import { EzsigndocumentGetObjectV1ResponseMPayload } from './ezsigndocument-get-object-v1-response-mpayload';

/**
 * @type EzsigndocumentGetObjectV1Response
 * Response for the /1/object/ezsigndocument/getDownloadUrl API Request
 * @export
 */
export type EzsigndocumentGetObjectV1Response = CommonResponse & EzsigndocumentGetObjectV1ResponseAllOf;


