/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EzsigntemplateglobalsignerResponse } from './ezsigntemplateglobalsigner-response';

/**
 * @type EzsigntemplateglobalsignerResponseCompound
 * A Ezsigntemplateglobalsigner Object
 * @export
 */
/*export type EzsigntemplateglobalsignerResponseCompound = EzsigntemplateglobalsignerResponse;*/
export interface EzsigntemplateglobalsignerResponseCompound {
}


/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsigntemplateglobalsignerResponseCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsigntemplateglobalsignerResponseCompound
 */
export class DataObjectEzsigntemplateglobalsignerResponseCompound {
}

/**
 * @export 
 * A EzsigntemplateglobalsignerResponseCompound Validation Object
 * @class ValidationObjectEzsigntemplateglobalsignerResponseCompound
 */
export class ValidationObjectEzsigntemplateglobalsignerResponseCompound {
} 


