/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldEEzsignfolderStep } from './field-eezsignfolder-step';
// May contain unused imports in some cases
// @ts-ignore
import type { FieldEEzsignfoldertypePrivacylevel } from './field-eezsignfoldertype-privacylevel';

/**
 * An Ezsignfolder List Element
 * @export
 * @interface EzsignfolderListElement
 */
export interface EzsignfolderListElement {
    /**
     * The unique ID of the Ezsignfolder
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'pkiEzsignfolderID': number;*/
    'pkiEzsignfolderID': number;
    /**
     * The unique ID of the Ezsignfoldertype.
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'fkiEzsignfoldertypeID': number;*/
    'fkiEzsignfoldertypeID': number;
    /**
     * 
     * @type {FieldEEzsignfoldertypePrivacylevel}
     * @memberof EzsignfolderListElement
     */
    /*'eEzsignfoldertypePrivacylevel': FieldEEzsignfoldertypePrivacylevel;*/
    'eEzsignfoldertypePrivacylevel': FieldEEzsignfoldertypePrivacylevel;
    /**
     * The name of the Ezsignfoldertype in the language of the requester
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'sEzsignfoldertypeNameX': string;*/
    'sEzsignfoldertypeNameX': string;
    /**
     * The description of the Ezsignfolder
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'sEzsignfolderDescription': string;*/
    'sEzsignfolderDescription': string;
    /**
     * 
     * @type {FieldEEzsignfolderStep}
     * @memberof EzsignfolderListElement
     */
    /*'eEzsignfolderStep': FieldEEzsignfolderStep;*/
    'eEzsignfolderStep': FieldEEzsignfolderStep;
    /**
     * The date and time at which the object was created
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtCreatedDate': string;*/
    'dtCreatedDate': string;
    /**
     * The date and time at which the Ezsignfolder will be sent in the future.
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtEzsignfolderDelayedsenddate'?: string;*/
    'dtEzsignfolderDelayedsenddate'?: string;
    /**
     * The date and time at which the Ezsignfolder was sent the last time.
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtEzsignfolderSentdate'?: string;*/
    'dtEzsignfolderSentdate'?: string;
    /**
     * The maximum date and time at which the Ezsignfolder can be signed.
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtEzsignfolderDuedate'?: string;*/
    'dtEzsignfolderDuedate'?: string;
    /**
     * The total number of Ezsigndocument in the folder
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'iEzsigndocument': number;*/
    'iEzsigndocument': number;
    /**
     * The total number of Ezsigndocument in the folder that were saved in the edm system
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'iEzsigndocumentEdm': number;*/
    'iEzsigndocumentEdm': number;
    /**
     * The total number of signature blocks in all Ezsigndocuments in the folder
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'iEzsignsignature': number;*/
    'iEzsignsignature': number;
    /**
     * The total number of already signed signature blocks in all Ezsigndocuments in the folder
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'iEzsignsignatureSigned': number;*/
    'iEzsignsignatureSigned': number;
    /**
     * The total number of Ezsignformfieldgroup in all Ezsigndocuments in the folder
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'iEzsignformfieldgroup': number;*/
    'iEzsignformfieldgroup': number;
    /**
     * The total number of completed Ezsignformfieldgroup in all Ezsigndocuments in the folder
     * @type {number}
     * @memberof EzsignfolderListElement
     */
    /*'iEzsignformfieldgroupCompleted': number;*/
    'iEzsignformfieldgroupCompleted': number;
    /**
     * Whether the Ezsignform/Ezsignsignatures has dependencies or not
     * @type {boolean}
     * @memberof EzsignfolderListElement
     */
    /*'bEzsignformHasdependencies'?: boolean;*/
    'bEzsignformHasdependencies'?: boolean;
    /**
     * Percentage of Ezsignform/Ezsignsignatures has completed
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dEzsignfolderCompletedpercentage': string;*/
    'dEzsignfolderCompletedpercentage': string;
    /**
     * Percentage of Ezsignform has completed
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dEzsignfolderFormcompletedpercentage': string;*/
    'dEzsignfolderFormcompletedpercentage': string;
    /**
     * Percentage of Ezsignsignatures has signed
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dEzsignfolderSignaturecompletedpercentage': string;*/
    'dEzsignfolderSignaturecompletedpercentage': string;
    /**
     * The date and time at which the Ezsignfolder was closed. Either by applying the last signature or by completing it prematurely.
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtEzsignfolderClose'?: string;*/
    'dtEzsignfolderClose'?: string;
    /**
     * The date and time at which the Ezsignfolder was archived.
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtEzsignfolderArchive'?: string;*/
    'dtEzsignfolderArchive'?: string;
    /**
     * The date and time at which the Ezsignfolder was disposed.
     * @type {string}
     * @memberof EzsignfolderListElement
     */
    /*'dtEzsignfolderDispose'?: string;*/
    'dtEzsignfolderDispose'?: string;
    /**
     * Whether the Ezsignfolder has an Ezsignsignatures that need to be signed or an Ezsignformfieldgroups that need to be filled by the current user
     * @type {boolean}
     * @memberof EzsignfolderListElement
     */
    /*'bEzsignfolderSigner'?: boolean;*/
    'bEzsignfolderSigner'?: boolean;
}


/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A EzsignfolderListElement Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignfolderListElement
 */
export class DataObjectEzsignfolderListElement {
   pkiEzsignfolderID:number = 0
   fkiEzsignfoldertypeID:number = 0
   eEzsignfoldertypePrivacylevel:FieldEEzsignfoldertypePrivacylevel = 'User'
   sEzsignfoldertypeNameX:string = ''
   sEzsignfolderDescription:string = ''
   eEzsignfolderStep:FieldEEzsignfolderStep = 'Unsent'
   dtCreatedDate:string = ''
   dtEzsignfolderDelayedsenddate?:string = undefined
   dtEzsignfolderSentdate?:string = undefined
   dtEzsignfolderDuedate?:string = undefined
   iEzsigndocument:number = 0
   iEzsigndocumentEdm:number = 0
   iEzsignsignature:number = 0
   iEzsignsignatureSigned:number = 0
   iEzsignformfieldgroup:number = 0
   iEzsignformfieldgroupCompleted:number = 0
   bEzsignformHasdependencies?:boolean = undefined
   dEzsignfolderCompletedpercentage:string = ''
   dEzsignfolderFormcompletedpercentage:string = ''
   dEzsignfolderSignaturecompletedpercentage:string = ''
   dtEzsignfolderClose?:string = undefined
   dtEzsignfolderArchive?:string = undefined
   dtEzsignfolderDispose?:string = undefined
   bEzsignfolderSigner?:boolean = undefined
}

/**
 * @export 
 * A EzsignfolderListElement Validation Object
 * @class ValidationObjectEzsignfolderListElement
 */
export class ValidationObjectEzsignfolderListElement {
   pkiEzsignfolderID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiEzsignfoldertypeID = {
      type: 'integer',
      minimum: 0,
      maximum: 65535,
      required: true
   }
   eEzsignfoldertypePrivacylevel = {
      type: 'enum',
      allowableValues: ['User','Usergroup'],
      required: true
   }
   sEzsignfoldertypeNameX = {
      type: 'string',
      required: true
   }
   sEzsignfolderDescription = {
      type: 'string',
      pattern: /^.{0,75}$/,
      required: true
   }
   eEzsignfolderStep = {
      type: 'enum',
      allowableValues: ['Unsent','PendingSend','Sent','PartiallySigned','Expired','Completed','Archived','Disposed'],
      required: true
   }
   dtCreatedDate = {
      type: 'string',
      required: true
   }
   dtEzsignfolderDelayedsenddate = {
      type: 'string',
      required: false
   }
   dtEzsignfolderSentdate = {
      type: 'string',
      required: false
   }
   dtEzsignfolderDuedate = {
      type: 'string',
      required: false
   }
   iEzsigndocument = {
      type: 'integer',
      required: true
   }
   iEzsigndocumentEdm = {
      type: 'integer',
      required: true
   }
   iEzsignsignature = {
      type: 'integer',
      required: true
   }
   iEzsignsignatureSigned = {
      type: 'integer',
      required: true
   }
   iEzsignformfieldgroup = {
      type: 'integer',
      required: true
   }
   iEzsignformfieldgroupCompleted = {
      type: 'integer',
      required: true
   }
   bEzsignformHasdependencies = {
      type: 'boolean',
      required: false
   }
   dEzsignfolderCompletedpercentage = {
      type: 'string',
      pattern: /^-{0,1}[\d]{1,3}?\.[\d]{2}$/,
      required: true
   }
   dEzsignfolderFormcompletedpercentage = {
      type: 'string',
      pattern: /^-{0,1}[\d]{1,3}?\.[\d]{2}$/,
      required: true
   }
   dEzsignfolderSignaturecompletedpercentage = {
      type: 'string',
      pattern: /^-{0,1}[\d]{1,3}?\.[\d]{2}$/,
      required: true
   }
   dtEzsignfolderClose = {
      type: 'string',
      required: false
   }
   dtEzsignfolderArchive = {
      type: 'string',
      required: false
   }
   dtEzsignfolderDispose = {
      type: 'string',
      required: false
   }
   bEzsignfolderSigner = {
      type: 'boolean',
      required: false
   }
} 


