/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.9
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EzsignbulksendtransmissionResponse } from './ezsignbulksendtransmission-response';

/**
 * Payload for POST /1/object/ezsignbulksend/{pkiEzsignbulksendID}/createEzsignbulksendtransmission
 * @export
 * @interface EzsignbulksendCreateEzsignbulksendtransmissionV1ResponseMPayload
 */
export interface EzsignbulksendCreateEzsignbulksendtransmissionV1ResponseMPayload {
    /**
     * 
     * @type {EzsignbulksendtransmissionResponse}
     * @memberof EzsignbulksendCreateEzsignbulksendtransmissionV1ResponseMPayload
     */
    'objEzsignbulksendtransmission': EzsignbulksendtransmissionResponse;
}

