/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsignfoldersignerassociationResponseCompound } from './ezsignfoldersignerassociation-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { EzsignfoldersignerassociationResponseCompoundUser } from './ezsignfoldersignerassociation-response-compound-user';
// May contain unused imports in some cases
// @ts-ignore
import { EzsignsignerResponseCompound } from './ezsignsigner-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { EzsignsignergroupResponseCompound } from './ezsignsignergroup-response-compound';
// May contain unused imports in some cases
// @ts-ignore
import { UsergroupResponseCompound } from './usergroup-response-compound';

/**
 * @type EzsignfoldersignerassociationGetObjectV1ResponseMPayload
 * Payload for GET /1/object/ezsignfoldersignerassociation/{pkiEzsignfoldersignerassociationID}
 * @export
 */
export type EzsignfoldersignerassociationGetObjectV1ResponseMPayload = EzsignfoldersignerassociationResponseCompound;


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzsignsignergroupResponseCompound } from './'
// @ts-ignore
import { DataObjectEzsignfoldersignerassociationResponseCompoundUser } from './'
// @ts-ignore
import { DataObjectUsergroupResponseCompound } from './'
// @ts-ignore
import { DataObjectEzsignsignerResponseCompound } from './'
// @ts-ignore
import { ValidationObjectEzsignsignergroupResponseCompound } from './'
// @ts-ignore
import { ValidationObjectEzsignfoldersignerassociationResponseCompoundUser } from './'
// @ts-ignore
import { ValidationObjectUsergroupResponseCompound } from './'
// @ts-ignore
import { ValidationObjectEzsignsignerResponseCompound } from './'

/**
 * @export 
 * A EzsignfoldersignerassociationGetObjectV1ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignfoldersignerassociationGetObjectV1ResponseMPayload
 */
export class DataObjectEzsignfoldersignerassociationGetObjectV1ResponseMPayload {
    pkiEzsignfoldersignerassociationID:number = 0
    fkiEzsignfolderID:number = 0
    bEzsignfoldersignerassociationDelayedsend:boolean = false
    bEzsignfoldersignerassociationReceivecopy:boolean = false
    tEzsignfoldersignerassociationMessage:string = ''
    objEzsignsignergroup?:EzsignsignergroupResponseCompound = undefined
    objUser?:EzsignfoldersignerassociationResponseCompoundUser = undefined
    objUsergroup?:UsergroupResponseCompound = undefined
    objEzsignsigner?:EzsignsignerResponseCompound = undefined
}

/**
 * @export 
 * A EzsignfoldersignerassociationGetObjectV1ResponseMPayload Validation Object
 * @class ValidationObjectEzsignfoldersignerassociationGetObjectV1ResponseMPayload
 */
export class ValidationObjectEzsignfoldersignerassociationGetObjectV1ResponseMPayload {
   pkiEzsignfoldersignerassociationID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   fkiEzsignfolderID = {
      type: 'integer',
      minimum: 0,
      required: true
   }
   bEzsignfoldersignerassociationDelayedsend = {
      type: 'boolean',
      required: true
   }
   bEzsignfoldersignerassociationReceivecopy = {
      type: 'boolean',
      required: true
   }
   tEzsignfoldersignerassociationMessage = {
      type: 'string',
      required: true
   }
   objEzsignsignergroup = new ValidationObjectEzsignsignergroupResponseCompound()
   objUser = new ValidationObjectEzsignfoldersignerassociationResponseCompoundUser()
   objUsergroup = new ValidationObjectUsergroupResponseCompound()
   objEzsignsigner = new ValidationObjectEzsignsignerResponseCompound()
} 


