/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonFile } from './common-file';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomCreditcardRequest } from './custom-creditcard-request';

/**
 * Request for POST /1/object/ezsignsignature/{pkiEzsignsignatureID}/sign
 */
export interface EzsignsignatureSignV1Request {
    /**
     * The unique ID of the Ezsignsigningreason
     */
    /*'fkiEzsignsigningreasonID'?: number;*/
    'fkiEzsignsigningreasonID'?: number;
    /**
     * The unique ID of the Font
     */
    /*'fkiFontID'?: number;*/
    'fkiFontID'?: number;
    /**
     * The amount of the Creditcard signature
     */
    /*'dEzsignsignatureCreditcardamount'?: string;*/
    'dEzsignsignatureCreditcardamount'?: string;
    /**
     * The value required for the Ezsignsignature.  This can only be set if eEzsignsignatureType is **City**, **FieldText** or **FieldTextarea**
     */
    /*'sValue'?: string;*/
    'sValue'?: string;
    /**
     * Whether the attachment are accepted or refused.  This can only be set if eEzsignsignatureType is **AttachmentsConfirmation**
     */
    /*'eAttachmentsConfirmationDecision'?: EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum;*/
    'eAttachmentsConfirmationDecision'?: EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum;
    /**
     * The reason of refused.  This can only be set if eEzsignsignatureType is **AttachmentsConfirmation**
     */
    /*'sAttachmentsRefusalReason'?: string;*/
    'sAttachmentsRefusalReason'?: string;
    /**
     * The SVG of the signature.  This can only be set if eEzsignsignatureType is **Signature**_/_**Initials** and **bIsAutomatic** is false
     */
    /*'sSvg'?: string;*/
    'sSvg'?: string;
    /*'a_objFile'?: Array<CommonFile>;*/
    'a_objFile'?: Array<CommonFile>;
    /*'objCreditcard'?: CustomCreditcardRequest;*/
    'objCreditcard'?: CustomCreditcardRequest;
    /**
     * Indicates if the Ezsignsignature was part of an automatic process or not.  This can only be true if eEzsignsignatureType is **Acknowledgement**, **City**, **Signature**, **Initials** or **Stamp**. 
     */
    /*'bIsAutomatic': boolean;*/
    'bIsAutomatic': boolean;
}

export const EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum = {
    Accepted: 'Accepted',
    Refused: 'Refused',
} as const;

export type EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum = typeof EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum[keyof typeof EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum];

/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCustomCreditcardRequest } from './'
// @ts-ignore
import { ValidationObjectCustomCreditcardRequest } from './'

/**
 * @export 
 * A EzsignsignatureSignV1Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignsignatureSignV1Request
 */
export class DataObjectEzsignsignatureSignV1Request {
   fkiEzsignsigningreasonID?:number = undefined
   fkiFontID?:number = undefined
   dEzsignsignatureCreditcardamount?:string = undefined
   sValue?:string = undefined
   eAttachmentsConfirmationDecision?:EzsignsignatureSignV1RequestEAttachmentsConfirmationDecisionEnum = undefined
   sAttachmentsRefusalReason?:string = undefined
   sSvg?:string = undefined
   a_objFile?:Array<CommonFile> = undefined
   objCreditcard?:CustomCreditcardRequest = undefined
   bIsAutomatic:boolean = false
}

/**
 * @export 
 * A EzsignsignatureSignV1Request Validation Object
 * @class ValidationObjectEzsignsignatureSignV1Request
 */
export class ValidationObjectEzsignsignatureSignV1Request {
   fkiEzsignsigningreasonID = {
      type: 'integer',
      minimum: 0,
      maximum: 255,
      required: false
   }
   fkiFontID = {
      type: 'integer',
      minimum: 0,
      required: false
   }
   dEzsignsignatureCreditcardamount = {
      type: 'string',
      pattern: /^[\d]{1,9}?\.[\d]{2}$/,
      required: false
   }
   sValue = {
      type: 'string',
      required: false
   }
   eAttachmentsConfirmationDecision = {
      type: 'string',
      required: false
   }
   sAttachmentsRefusalReason = {
      type: 'string',
      required: false
   }
   sSvg = {
      type: 'string',
      pattern: /^.{0,65535}$/,
      required: false
   }
   a_objFile = {
      type: 'array',
      required: false
   }
   objCreditcard = new ValidationObjectCustomCreditcardRequest()
   bIsAutomatic = {
      type: 'boolean',
      required: true
   }
} 


