/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EzsignbulksendResponseCompound } from './ezsignbulksend-response-compound';

/**
 * Payload for GET /2/object/ezsignbulksend/{pkiEzsignbulksendID}
 * @export
 * @interface EzsignbulksendGetObjectV2ResponseMPayload
 */
export interface EzsignbulksendGetObjectV2ResponseMPayload {
    /**
     * 
     * @type {EzsignbulksendResponseCompound}
     * @memberof EzsignbulksendGetObjectV2ResponseMPayload
     */
    /*'objEzsignbulksend': EzsignbulksendResponseCompound;*/
    'objEzsignbulksend': EzsignbulksendResponseCompound;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectEzsignbulksendResponseCompound } from './'
// @ts-ignore
import { ValidationObjectEzsignbulksendResponseCompound } from './'

/**
 * @export 
 * A EzsignbulksendGetObjectV2ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectEzsignbulksendGetObjectV2ResponseMPayload
 */
export class DataObjectEzsignbulksendGetObjectV2ResponseMPayload {
   objEzsignbulksend:EzsignbulksendResponseCompound = new DataObjectEzsignbulksendResponseCompound()
}

/**
 * @export 
 * A EzsignbulksendGetObjectV2ResponseMPayload Validation Object
 * @class ValidationObjectEzsignbulksendGetObjectV2ResponseMPayload
 */
export class ValidationObjectEzsignbulksendGetObjectV2ResponseMPayload {
   objEzsignbulksend = new ValidationObjectEzsignbulksendResponseCompound()
} 


