/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The verticalalignment of the Ezsigntemplateglobalannotation
 */

export const FieldEEzsigntemplateglobalannotationVerticalalignment = {
    Bottom: 'Bottom',
    Middle: 'Middle',
    Top: 'Top',
} as const;

export type FieldEEzsigntemplateglobalannotationVerticalalignment = typeof FieldEEzsigntemplateglobalannotationVerticalalignment[keyof typeof FieldEEzsigntemplateglobalannotationVerticalalignment];



