/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Agent schedule type.
 */

export const FieldEAgentSchedule = {
    Full_time: 'Full-time',
    Part_time: 'Part-time',
} as const;

export type FieldEAgentSchedule = typeof FieldEAgentSchedule[keyof typeof FieldEAgentSchedule];



