/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import { FranchiseofficeGetAutocompleteV2ResponseAllOf } from './franchiseoffice-get-autocomplete-v2-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { FranchiseofficeGetAutocompleteV2ResponseMPayload } from './franchiseoffice-get-autocomplete-v2-response-mpayload';

/**
 * @type FranchiseofficeGetAutocompleteV2Response
 * Response for GET /2/object/franchiseoffice/getAutocomplete
 * @export
 */
export type FranchiseofficeGetAutocompleteV2Response = CommonResponse & FranchiseofficeGetAutocompleteV2ResponseAllOf;


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectFranchiseofficeGetAutocompleteV2ResponseMPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectFranchiseofficeGetAutocompleteV2ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'

/**
 * @export 
 * A FranchiseofficeGetAutocompleteV2Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectFranchiseofficeGetAutocompleteV2Response
 */
export class DataObjectFranchiseofficeGetAutocompleteV2Response {
    mPayload:FranchiseofficeGetAutocompleteV2ResponseMPayload = new DataObjectFranchiseofficeGetAutocompleteV2ResponseMPayload()
    objDebugPayload?:CommonResponseObjDebugPayload = undefined
    objDebug?:CommonResponseObjDebug = undefined
}

/**
 * @export 
 * A FranchiseofficeGetAutocompleteV2Response Validation Object
 * @class ValidationObjectFranchiseofficeGetAutocompleteV2Response
 */
export class ValidationObjectFranchiseofficeGetAutocompleteV2Response {
   mPayload = new ValidationObjectFranchiseofficeGetAutocompleteV2ResponseMPayload()
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
} 


