/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { InscriptionnotauthenticatedGetObjectV2ResponseMPayload } from './inscriptionnotauthenticated-get-object-v2-response-mpayload';

/**
 * @type InscriptionnotauthenticatedGetObjectV2Response
 * Response for GET /2/object/inscriptionnotauthenticated/{pkiInscriptionnotauthenticatedID}
 */
/*export type InscriptionnotauthenticatedGetObjectV2Response = CommonResponse;*/
export interface InscriptionnotauthenticatedGetObjectV2Response {
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof InscriptionnotauthenticatedGetObjectV2Response
     */
    objDebugPayload:CommonResponseObjDebugPayload 
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof InscriptionnotauthenticatedGetObjectV2Response
     */
    objDebug?:CommonResponseObjDebug 
    /**
     * 
     * @type {InscriptionnotauthenticatedGetObjectV2ResponseMPayload}
     * @memberof InscriptionnotauthenticatedGetObjectV2Response
     */
    mPayload:InscriptionnotauthenticatedGetObjectV2ResponseMPayload 
}


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { DataObjectInscriptionnotauthenticatedGetObjectV2ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectInscriptionnotauthenticatedGetObjectV2ResponseMPayload } from './'

/**
 * @export 
 * A InscriptionnotauthenticatedGetObjectV2Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectInscriptionnotauthenticatedGetObjectV2Response
 */
export class DataObjectInscriptionnotauthenticatedGetObjectV2Response {
    objDebugPayload:CommonResponseObjDebugPayload = new DataObjectCommonResponseObjDebugPayload()
    objDebug?:CommonResponseObjDebug = undefined
    mPayload:InscriptionnotauthenticatedGetObjectV2ResponseMPayload = new DataObjectInscriptionnotauthenticatedGetObjectV2ResponseMPayload()
}

/**
 * @export 
 * A InscriptionnotauthenticatedGetObjectV2Response Validation Object
 * @class ValidationObjectInscriptionnotauthenticatedGetObjectV2Response
 */
export class ValidationObjectInscriptionnotauthenticatedGetObjectV2Response {
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
   mPayload = new ValidationObjectInscriptionnotauthenticatedGetObjectV2ResponseMPayload()
} 


