/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import { InscriptionGetCommunicationsendersV1ResponseMPayload } from './inscription-get-communicationsenders-v1-response-mpayload';

/**
 * @type InscriptionGetCommunicationsendersV1Response
 * Response for GET /1/object/inscription/{pkiInscriptionID}/getCommunicationrecipients
 * @export
 */
/*export type InscriptionGetCommunicationsendersV1Response = CommonResponse;*/
export interface InscriptionGetCommunicationsendersV1Response {
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof InscriptionGetCommunicationsendersV1Response
     */
    objDebugPayload:CommonResponseObjDebugPayload 
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof InscriptionGetCommunicationsendersV1Response
     */
    objDebug?:CommonResponseObjDebug 
    /**
     * 
     * @type {InscriptionGetCommunicationsendersV1ResponseMPayload}
     * @memberof InscriptionGetCommunicationsendersV1Response
     */
    mPayload:InscriptionGetCommunicationsendersV1ResponseMPayload 
}


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { DataObjectInscriptionGetCommunicationsendersV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectInscriptionGetCommunicationsendersV1ResponseMPayload } from './'

/**
 * @export 
 * A InscriptionGetCommunicationsendersV1Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectInscriptionGetCommunicationsendersV1Response
 */
export class DataObjectInscriptionGetCommunicationsendersV1Response {
    objDebugPayload:CommonResponseObjDebugPayload = new DataObjectCommonResponseObjDebugPayload()
    objDebug?:CommonResponseObjDebug = undefined
    mPayload:InscriptionGetCommunicationsendersV1ResponseMPayload = new DataObjectInscriptionGetCommunicationsendersV1ResponseMPayload()
}

/**
 * @export 
 * A InscriptionGetCommunicationsendersV1Response Validation Object
 * @class ValidationObjectInscriptionGetCommunicationsendersV1Response
 */
export class ValidationObjectInscriptionGetCommunicationsendersV1Response {
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
   mPayload = new ValidationObjectInscriptionGetCommunicationsendersV1ResponseMPayload()
} 


