/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaymenttermGetListV1ResponseMPayload } from './paymentterm-get-list-v1-response-mpayload';

/**
 * 
 * @export
 * @interface PaymenttermGetListV1ResponseAllOf
 */
export interface PaymenttermGetListV1ResponseAllOf {
    /**
     * 
     * @type {PaymenttermGetListV1ResponseMPayload}
     * @memberof PaymenttermGetListV1ResponseAllOf
     */
    'mPayload': PaymenttermGetListV1ResponseMPayload;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectPaymenttermGetListV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectPaymenttermGetListV1ResponseMPayload } from './'

/**
 * @export 
 * A PaymenttermGetListV1ResponseAllOf Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectPaymenttermGetListV1ResponseAllOf
 */
export class DataObjectPaymenttermGetListV1ResponseAllOf {
   mPayload:PaymenttermGetListV1ResponseMPayload = new DataObjectPaymenttermGetListV1ResponseMPayload()
}

/**
 * @export 
 * A PaymenttermGetListV1ResponseAllOf Validation Object
 * @class ValidationObjectPaymenttermGetListV1ResponseAllOf
 */
export class ValidationObjectPaymenttermGetListV1ResponseAllOf {
   mPayload = new ValidationObjectPaymenttermGetListV1ResponseMPayload()
} 


