/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A Paymentterm AutocompleteElement Response
 * @export
 * @interface PaymenttermAutocompleteElementResponse
 */
export interface PaymenttermAutocompleteElementResponse {
    /**
     * The unique ID of the Paymentterm
     * @type {number}
     * @memberof PaymenttermAutocompleteElementResponse
     */
    'pkiPaymenttermID': number;
    /**
     * The description of the Paymentterm in the language of the requester
     * @type {string}
     * @memberof PaymenttermAutocompleteElementResponse
     */
    'sPaymenttermDescriptionX': string;
    /**
     * Whether the Paymentterm is active or not
     * @type {boolean}
     * @memberof PaymenttermAutocompleteElementResponse
     */
    'bPaymenttermIsactive': boolean;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A PaymenttermAutocompleteElementResponse Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectPaymenttermAutocompleteElementResponse
 */
export class DataObjectPaymenttermAutocompleteElementResponse {
   pkiPaymenttermID:number = 0
   sPaymenttermDescriptionX:string = ''
   bPaymenttermIsactive:boolean = false
}

/**
 * @export 
 * A PaymenttermAutocompleteElementResponse Validation Object
 * @class ValidationObjectPaymenttermAutocompleteElementResponse
 */
export class ValidationObjectPaymenttermAutocompleteElementResponse {
   pkiPaymenttermID = {
      type: 'integer',
      required: true
   }
   sPaymenttermDescriptionX = {
      type: 'string',
      pattern: '/^.{1,40}$/',
      required: true
   }
   bPaymenttermIsactive = {
      type: 'boolean',
      required: true
   }
} 


