/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldEPhoneType } from './field-ephone-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PhoneResponse } from './phone-response';

/**
 * @type PhoneResponseCompound
 * A Phone Object and children to create a complete structure
 * @export
 */
/*export type PhoneResponseCompound = PhoneResponse;*/
export interface PhoneResponseCompound {
    /**
     * Indicate the phone number is an international phone number.
     * @type {boolean}
     * @memberof PhoneResponseCompound
     */
    bPhoneInternational?:boolean 
}



/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A PhoneResponseCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectPhoneResponseCompound
 */
export class DataObjectPhoneResponseCompound {
    bPhoneInternational?:boolean = undefined
}

/**
 * @export 
 * A PhoneResponseCompound Validation Object
 * @class ValidationObjectPhoneResponseCompound
 */
export class ValidationObjectPhoneResponseCompound {
   bPhoneInternational = {
      type: 'boolean',
      required: false
   }
} 


