/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseGetList } from './common-response-get-list';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebugPayloadGetList } from './common-response-obj-debug-payload-get-list';
// May contain unused imports in some cases
// @ts-ignore
import type { SupplierGetListV1ResponseMPayload } from './supplier-get-list-v1-response-mpayload';

/**
 * @type SupplierGetListV1Response
 * Response for GET /1/object/supplier/getList
 */
/*export type SupplierGetListV1Response = CommonResponseGetList;*/
export interface SupplierGetListV1Response {
    /**
     * 
     * @type {CommonResponseObjDebugPayloadGetList}
     * @memberof SupplierGetListV1Response
     */
    objDebugPayload:CommonResponseObjDebugPayloadGetList 
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof SupplierGetListV1Response
     */
    objDebug?:CommonResponseObjDebug 
    /**
     * 
     * @type {SupplierGetListV1ResponseMPayload}
     * @memberof SupplierGetListV1Response
     */
    mPayload:SupplierGetListV1ResponseMPayload 
}


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayloadGetList } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { DataObjectSupplierGetListV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayloadGetList } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectSupplierGetListV1ResponseMPayload } from './'

/**
 * @export 
 * A SupplierGetListV1Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectSupplierGetListV1Response
 */
export class DataObjectSupplierGetListV1Response {
    objDebugPayload:CommonResponseObjDebugPayloadGetList = new DataObjectCommonResponseObjDebugPayloadGetList()
    objDebug?:CommonResponseObjDebug = undefined
    mPayload:SupplierGetListV1ResponseMPayload = new DataObjectSupplierGetListV1ResponseMPayload()
}

/**
 * @export 
 * A SupplierGetListV1Response Validation Object
 * @class ValidationObjectSupplierGetListV1Response
 */
export class ValidationObjectSupplierGetListV1Response {
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayloadGetList()
   objDebug = new ValidationObjectCommonResponseObjDebug()
   mPayload = new ValidationObjectSupplierGetListV1ResponseMPayload()
} 


