/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SupplyRequestCompound } from './supply-request-compound';

/**
 * Request for PUT /1/object/supply/{pkiSupplyID}
 * @export
 * @interface SupplyEditObjectV1Request
 */
export interface SupplyEditObjectV1Request {
    /**
     * 
     * @type {SupplyRequestCompound}
     * @memberof SupplyEditObjectV1Request
     */
    /*'objSupply': SupplyRequestCompound;*/
    'objSupply': SupplyRequestCompound;
}
/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectSupplyRequestCompound } from './'
// @ts-ignore
import { ValidationObjectSupplyRequestCompound } from './'

/**
 * @export 
 * A SupplyEditObjectV1Request Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectSupplyEditObjectV1Request
 */
export class DataObjectSupplyEditObjectV1Request {
   objSupply:SupplyRequestCompound = new DataObjectSupplyRequestCompound()
}

/**
 * @export 
 * A SupplyEditObjectV1Request Validation Object
 * @class ValidationObjectSupplyEditObjectV1Request
 */
export class ValidationObjectSupplyEditObjectV1Request {
   objSupply = new ValidationObjectSupplyRequestCompound()
} 


