/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import { UsergroupmembershipGetObjectV2ResponseAllOf } from './usergroupmembership-get-object-v2-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { UsergroupmembershipGetObjectV2ResponseMPayload } from './usergroupmembership-get-object-v2-response-mpayload';

/**
 * @type UsergroupmembershipGetObjectV2Response
 * Response for GET /2/object/usergroupmembership/{pkiUsergroupmembershipID}
 * @export
 */
export type UsergroupmembershipGetObjectV2Response = CommonResponse & UsergroupmembershipGetObjectV2ResponseAllOf;


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectUsergroupmembershipGetObjectV2ResponseMPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectUsergroupmembershipGetObjectV2ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'

/**
 * @export 
 * A UsergroupmembershipGetObjectV2Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectUsergroupmembershipGetObjectV2Response
 */
export class DataObjectUsergroupmembershipGetObjectV2Response {
    mPayload:UsergroupmembershipGetObjectV2ResponseMPayload = new DataObjectUsergroupmembershipGetObjectV2ResponseMPayload()
    objDebugPayload?:CommonResponseObjDebugPayload = undefined
    objDebug?:CommonResponseObjDebug = undefined
}

/**
 * @export 
 * A UsergroupmembershipGetObjectV2Response Validation Object
 * @class ValidationObjectUsergroupmembershipGetObjectV2Response
 */
export class ValidationObjectUsergroupmembershipGetObjectV2Response {
   mPayload = new ValidationObjectUsergroupmembershipGetObjectV2ResponseMPayload()
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
} 


