/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserstagedListElement } from './userstaged-list-element';

/**
 * 
 * @export
 * @interface UserstagedGetListV1ResponseMPayloadAllOf
 */
export interface UserstagedGetListV1ResponseMPayloadAllOf {
    /**
     * 
     * @type {Array<UserstagedListElement>}
     * @memberof UserstagedGetListV1ResponseMPayloadAllOf
     */
    'a_objUserstaged': Array<UserstagedListElement>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A UserstagedGetListV1ResponseMPayloadAllOf Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectUserstagedGetListV1ResponseMPayloadAllOf
 */
export class DataObjectUserstagedGetListV1ResponseMPayloadAllOf {
   a_objUserstaged:Array<UserstagedListElement> = []
}

/**
 * @export 
 * A UserstagedGetListV1ResponseMPayloadAllOf Validation Object
 * @class ValidationObjectUserstagedGetListV1ResponseMPayloadAllOf
 */
export class ValidationObjectUserstagedGetListV1ResponseMPayloadAllOf {
   a_objUserstaged = {
      type: 'array',
      required: true
   }
} 


