/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponse } from './common-response';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebug } from './common-response-obj-debug';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';
// May contain unused imports in some cases
// @ts-ignore
import type { UserImpersonateV1ResponseMPayload } from './user-impersonate-v1-response-mpayload';

/**
 * @type UserImpersonateV1Response
 * Response for POST /1/object/user/{pkiUserID}/impersonate
 */
/*export type UserImpersonateV1Response = CommonResponse;*/
export interface UserImpersonateV1Response {
    /**
     * 
     * @type {CommonResponseObjDebugPayload}
     * @memberof UserImpersonateV1Response
     */
    objDebugPayload:CommonResponseObjDebugPayload 
    /**
     * 
     * @type {CommonResponseObjDebug}
     * @memberof UserImpersonateV1Response
     */
    objDebug?:CommonResponseObjDebug 
    /**
     * 
     * @type {UserImpersonateV1ResponseMPayload}
     * @memberof UserImpersonateV1Response
     */
    mPayload:UserImpersonateV1ResponseMPayload 
}


/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { DataObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { DataObjectUserImpersonateV1ResponseMPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebugPayload } from './'
// @ts-ignore
import { ValidationObjectCommonResponseObjDebug } from './'
// @ts-ignore
import { ValidationObjectUserImpersonateV1ResponseMPayload } from './'

/**
 * @export 
 * A UserImpersonateV1Response Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectUserImpersonateV1Response
 */
export class DataObjectUserImpersonateV1Response {
    objDebugPayload:CommonResponseObjDebugPayload = new DataObjectCommonResponseObjDebugPayload()
    objDebug?:CommonResponseObjDebug = undefined
    mPayload:UserImpersonateV1ResponseMPayload = new DataObjectUserImpersonateV1ResponseMPayload()
}

/**
 * @export 
 * A UserImpersonateV1Response Validation Object
 * @class ValidationObjectUserImpersonateV1Response
 */
export class ValidationObjectUserImpersonateV1Response {
   objDebugPayload = new ValidationObjectCommonResponseObjDebugPayload()
   objDebug = new ValidationObjectCommonResponseObjDebug()
   mPayload = new ValidationObjectUserImpersonateV1ResponseMPayload()
} 


