/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UsergroupResponseCompound } from './usergroup-response-compound';

/**
 * Response for GET /1/object/user/{pkiUserID}/getUsergroups
 * @export
 * @interface UserGetUsergroupsV1ResponseMPayload
 */
export interface UserGetUsergroupsV1ResponseMPayload {
    /**
     * 
     * @type {Array<UsergroupResponseCompound>}
     * @memberof UserGetUsergroupsV1ResponseMPayload
     */
    'a_objUsergroup': Array<UsergroupResponseCompound>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A UserGetUsergroupsV1ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectUserGetUsergroupsV1ResponseMPayload
 */
export class DataObjectUserGetUsergroupsV1ResponseMPayload {
   a_objUsergroup:Array<UsergroupResponseCompound> = []
}

/**
 * @export 
 * A UserGetUsergroupsV1ResponseMPayload Validation Object
 * @class ValidationObjectUserGetUsergroupsV1ResponseMPayload
 */
export class ValidationObjectUserGetUsergroupsV1ResponseMPayload {
   a_objUsergroup = {
      type: 'array',
      required: true
   }
} 


