/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserAutocompleteElementResponse } from './user-autocomplete-element-response';

/**
 * Payload for POST /2/object/user/getAutocomplete
 * @export
 * @interface UserGetAutocompleteV2ResponseMPayload
 */
export interface UserGetAutocompleteV2ResponseMPayload {
    /**
     * An array of User autocomplete element response.
     * @type {Array<UserAutocompleteElementResponse>}
     * @memberof UserGetAutocompleteV2ResponseMPayload
     */
    'a_objUser': Array<UserAutocompleteElementResponse>;
}
/**
 * @import
 * Imports Child Data Object
 */

/**
 * @export 
 * A UserGetAutocompleteV2ResponseMPayload Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectUserGetAutocompleteV2ResponseMPayload
 */
export class DataObjectUserGetAutocompleteV2ResponseMPayload {
   a_objUser:Array<UserAutocompleteElementResponse> = []
}

/**
 * @export 
 * A UserGetAutocompleteV2ResponseMPayload Validation Object
 * @class ValidationObjectUserGetAutocompleteV2ResponseMPayload
 */
export class ValidationObjectUserGetAutocompleteV2ResponseMPayload {
   a_objUser = {
      type: 'array',
      required: true
   }
} 


