/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldEVariableexpenseTaxable } from './field-evariableexpense-taxable';
// May contain unused imports in some cases
// @ts-ignore
import type { MultilingualVariableexpenseDescription } from './multilingual-variableexpense-description';
// May contain unused imports in some cases
// @ts-ignore
import type { VariableexpenseRequest } from './variableexpense-request';

/**
 * @type VariableexpenseRequestCompound
 * A Variableexpense Object and children
 * @export
 */
/*export type VariableexpenseRequestCompound = VariableexpenseRequest;*/
export interface VariableexpenseRequestCompound {
    /**
     * The unique ID of the Variableexpense
     * @type {number}
     * @memberof VariableexpenseRequestCompound
     */
    pkiVariableexpenseID?:number 
    /**
     * The code of the Variableexpense
     * @type {string}
     * @memberof VariableexpenseRequestCompound
     */
    sVariableexpenseCode:string 
    /**
     * 
     * @type {MultilingualVariableexpenseDescription}
     * @memberof VariableexpenseRequestCompound
     */
    objVariableexpenseDescription:MultilingualVariableexpenseDescription 
    /**
     * 
     * @type {FieldEVariableexpenseTaxable}
     * @memberof VariableexpenseRequestCompound
     */
    eVariableexpenseTaxable:FieldEVariableexpenseTaxable 
    /**
     * Whether the variableexpense is active or not
     * @type {boolean}
     * @memberof VariableexpenseRequestCompound
     */
    bVariableexpenseIsactive:boolean 
}



/**
 * @import
 * Imports Child Data Object
 */
// @ts-ignore
import { DataObjectMultilingualVariableexpenseDescription } from './'
// @ts-ignore
import { ValidationObjectMultilingualVariableexpenseDescription } from './'

/**
 * @export 
 * A VariableexpenseRequestCompound Data Object with automatic temporary default value
 * Use this object only for create an empty data object to assign a response from server
 * @class DataObjectVariableexpenseRequestCompound
 */
export class DataObjectVariableexpenseRequestCompound {
    pkiVariableexpenseID?:number = undefined
    sVariableexpenseCode:string = ''
    objVariableexpenseDescription:MultilingualVariableexpenseDescription = new DataObjectMultilingualVariableexpenseDescription()
    eVariableexpenseTaxable:FieldEVariableexpenseTaxable = 'Yes'
    bVariableexpenseIsactive:boolean = false
}

/**
 * @export 
 * A VariableexpenseRequestCompound Validation Object
 * @class ValidationObjectVariableexpenseRequestCompound
 */
export class ValidationObjectVariableexpenseRequestCompound {
   pkiVariableexpenseID = {
      type: 'integer',
      minimum: 1,
      maximum: 255,
      required: false
   }
   sVariableexpenseCode = {
      type: 'string',
      pattern: /^.{0,5}$/,
      required: true
   }
   objVariableexpenseDescription = new ValidationObjectMultilingualVariableexpenseDescription()
   eVariableexpenseTaxable = {
      type: 'enum',
      allowableValues: ['Yes','No','Included'],
      required: true
   }
   bVariableexpenseIsactive = {
      type: 'boolean',
      required: true
   }
} 


