/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CommonResponseError } from '../model';
// @ts-ignore
import { EzsigntemplateglobalGetAutocompleteV2Response } from '../model';
// @ts-ignore
import { EzsigntemplateglobalGetObjectV2Response } from '../model';
// @ts-ignore
import { HeaderAcceptLanguage } from '../model';
// @ts-ignore
import { RequestSignature, IHeadersData } from '../api/request-signature';
/**
 * ObjectEzsigntemplateglobalApi - axios parameter creator
 * @export
 */
export const ObjectEzsigntemplateglobalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the list of Ezsigntemplateglobal to be used in a dropdown or autocomplete control.
         * @summary Retrieve Ezsigntemplateglobals and IDs
         * @param {EzsigntemplateglobalGetAutocompleteV2SSelectorEnum} sSelector The type of Ezsigntemplateglobals to return
         * @param {EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum} [eFilterActive] Specify which results we want to display.
         * @param {string} [sQuery] Allow to filter the returned results
         * @param {HeaderAcceptLanguage} [acceptLanguage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ezsigntemplateglobalGetAutocompleteV2: async (sSelector: EzsigntemplateglobalGetAutocompleteV2SSelectorEnum, eFilterActive?: EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum, sQuery?: string, acceptLanguage?: HeaderAcceptLanguage, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sSelector' is not null or undefined
            assertParamExists('ezsigntemplateglobalGetAutocompleteV2', 'sSelector', sSelector)
            const localVarPath = `/2/object/ezsigntemplateglobal/getAutocomplete/{sSelector}`
                .replace(`{${"sSelector"}}`, encodeURIComponent(String(sSelector)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let basePath = DUMMY_BASE_URL
            if (configuration && configuration.basePath) basePath = configuration.basePath
            //const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            const localVarUrlObj = new URL(localVarPath, basePath);

            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (eFilterActive !== undefined) {
                localVarQueryParameter['eFilterActive'] = eFilterActive;
            }

            if (sQuery !== undefined) {
                localVarQueryParameter['sQuery'] = sQuery;
            }

            if (acceptLanguage != null) {
                localVarHeaderParameter['Accept-Language'] = typeof acceptLanguage === 'string'
                    ? acceptLanguage
                    : JSON.stringify(acceptLanguage);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            //localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = {...headersFromBaseOptions, ...localVarHeaderParameter,  ...options.headers};

            // Signature
            if (configuration && configuration.apiKey) {
                const secret = configuration.getSecret()
                if (secret) {
                    const headers:IHeadersData = {
                        authorization: configuration.apiKey as string,
                        secret: secret as string,
                        method: 'GET' as string,
                        url: basePath + toPathString(localVarUrlObj) as string,
                        body: localVarRequestOptions.data || '' as string
                    }
                    const signatureHeaders = RequestSignature.getHeaders(headers)
                    localVarRequestOptions.headers = { ...localVarRequestOptions.headers, ...signatureHeaders }
                } 
            }

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve an existing Ezsigntemplateglobal
         * @param {number} pkiEzsigntemplateglobalID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ezsigntemplateglobalGetObjectV2: async (pkiEzsigntemplateglobalID: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pkiEzsigntemplateglobalID' is not null or undefined
            assertParamExists('ezsigntemplateglobalGetObjectV2', 'pkiEzsigntemplateglobalID', pkiEzsigntemplateglobalID)
            const localVarPath = `/2/object/ezsigntemplateglobal/{pkiEzsigntemplateglobalID}`
                .replace(`{${"pkiEzsigntemplateglobalID"}}`, encodeURIComponent(String(pkiEzsigntemplateglobalID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let basePath = DUMMY_BASE_URL
            if (configuration && configuration.basePath) basePath = configuration.basePath
            //const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            const localVarUrlObj = new URL(localVarPath, basePath);

            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            //localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = {...headersFromBaseOptions, ...localVarHeaderParameter,  ...options.headers};

            // Signature
            if (configuration && configuration.apiKey) {
                const secret = configuration.getSecret()
                if (secret) {
                    const headers:IHeadersData = {
                        authorization: configuration.apiKey as string,
                        secret: secret as string,
                        method: 'GET' as string,
                        url: basePath + toPathString(localVarUrlObj) as string,
                        body: localVarRequestOptions.data || '' as string
                    }
                    const signatureHeaders = RequestSignature.getHeaders(headers)
                    localVarRequestOptions.headers = { ...localVarRequestOptions.headers, ...signatureHeaders }
                } 
            }

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ObjectEzsigntemplateglobalApi - functional programming interface
 * @export
 */
export const ObjectEzsigntemplateglobalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ObjectEzsigntemplateglobalApiAxiosParamCreator(configuration)
    return {
        /**
         * Get the list of Ezsigntemplateglobal to be used in a dropdown or autocomplete control.
         * @summary Retrieve Ezsigntemplateglobals and IDs
         * @param {EzsigntemplateglobalGetAutocompleteV2SSelectorEnum} sSelector The type of Ezsigntemplateglobals to return
         * @param {EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum} [eFilterActive] Specify which results we want to display.
         * @param {string} [sQuery] Allow to filter the returned results
         * @param {HeaderAcceptLanguage} [acceptLanguage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ezsigntemplateglobalGetAutocompleteV2(sSelector: EzsigntemplateglobalGetAutocompleteV2SSelectorEnum, eFilterActive?: EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum, sQuery?: string, acceptLanguage?: HeaderAcceptLanguage, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EzsigntemplateglobalGetAutocompleteV2Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ezsigntemplateglobalGetAutocompleteV2(sSelector, eFilterActive, sQuery, acceptLanguage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObjectEzsigntemplateglobalApi.ezsigntemplateglobalGetAutocompleteV2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve an existing Ezsigntemplateglobal
         * @param {number} pkiEzsigntemplateglobalID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ezsigntemplateglobalGetObjectV2(pkiEzsigntemplateglobalID: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EzsigntemplateglobalGetObjectV2Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ezsigntemplateglobalGetObjectV2(pkiEzsigntemplateglobalID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObjectEzsigntemplateglobalApi.ezsigntemplateglobalGetObjectV2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ObjectEzsigntemplateglobalApi - factory interface
 * @export
 */
export const ObjectEzsigntemplateglobalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ObjectEzsigntemplateglobalApiFp(configuration)
    return {
        /**
         * Get the list of Ezsigntemplateglobal to be used in a dropdown or autocomplete control.
         * @summary Retrieve Ezsigntemplateglobals and IDs
         * @param {EzsigntemplateglobalGetAutocompleteV2SSelectorEnum} sSelector The type of Ezsigntemplateglobals to return
         * @param {EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum} [eFilterActive] Specify which results we want to display.
         * @param {string} [sQuery] Allow to filter the returned results
         * @param {HeaderAcceptLanguage} [acceptLanguage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ezsigntemplateglobalGetAutocompleteV2(sSelector: EzsigntemplateglobalGetAutocompleteV2SSelectorEnum, eFilterActive?: EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum, sQuery?: string, acceptLanguage?: HeaderAcceptLanguage, options?: any): AxiosPromise<EzsigntemplateglobalGetAutocompleteV2Response> {
            return localVarFp.ezsigntemplateglobalGetAutocompleteV2(sSelector, eFilterActive, sQuery, acceptLanguage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve an existing Ezsigntemplateglobal
         * @param {number} pkiEzsigntemplateglobalID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ezsigntemplateglobalGetObjectV2(pkiEzsigntemplateglobalID: number, options?: any): AxiosPromise<EzsigntemplateglobalGetObjectV2Response> {
            return localVarFp.ezsigntemplateglobalGetObjectV2(pkiEzsigntemplateglobalID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ObjectEzsigntemplateglobalApi - object-oriented interface
 * @export
 * @class ObjectEzsigntemplateglobalApi
 * @extends {BaseAPI}
 */
export class ObjectEzsigntemplateglobalApi extends BaseAPI {
    /**
     * Get the list of Ezsigntemplateglobal to be used in a dropdown or autocomplete control.
     * @summary Retrieve Ezsigntemplateglobals and IDs
     * @param {EzsigntemplateglobalGetAutocompleteV2SSelectorEnum} sSelector The type of Ezsigntemplateglobals to return
     * @param {EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum} [eFilterActive] Specify which results we want to display.
     * @param {string} [sQuery] Allow to filter the returned results
     * @param {HeaderAcceptLanguage} [acceptLanguage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectEzsigntemplateglobalApi
     */
    public ezsigntemplateglobalGetAutocompleteV2(sSelector: EzsigntemplateglobalGetAutocompleteV2SSelectorEnum, eFilterActive?: EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum, sQuery?: string, acceptLanguage?: HeaderAcceptLanguage, options?: RawAxiosRequestConfig) {
        return ObjectEzsigntemplateglobalApiFp(this.configuration).ezsigntemplateglobalGetAutocompleteV2(sSelector, eFilterActive, sQuery, acceptLanguage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve an existing Ezsigntemplateglobal
     * @param {number} pkiEzsigntemplateglobalID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectEzsigntemplateglobalApi
     */
    public ezsigntemplateglobalGetObjectV2(pkiEzsigntemplateglobalID: number, options?: RawAxiosRequestConfig) {
        return ObjectEzsigntemplateglobalApiFp(this.configuration).ezsigntemplateglobalGetObjectV2(pkiEzsigntemplateglobalID, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const EzsigntemplateglobalGetAutocompleteV2SSelectorEnum = {
    All: 'All'
} as const;
export type EzsigntemplateglobalGetAutocompleteV2SSelectorEnum = typeof EzsigntemplateglobalGetAutocompleteV2SSelectorEnum[keyof typeof EzsigntemplateglobalGetAutocompleteV2SSelectorEnum];
/**
 * @export
 */
export const EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum = {
    All: 'All',
    Active: 'Active',
    Inactive: 'Inactive'
} as const;
export type EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum = typeof EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum[keyof typeof EzsigntemplateglobalGetAutocompleteV2EFilterActiveEnum];
