/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.4
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResponseError } from '../model';
// @ts-ignore
import type { PurchaseBatchDownloadV1Request } from '../model';
// @ts-ignore
import type { PurchaseGetAttachmentsV1Response } from '../model';
// @ts-ignore
import type { PurchaseImportIntoEDMV1Request } from '../model';
// @ts-ignore
import type { PurchaseImportIntoEDMV1Response } from '../model';
// @ts-ignore
import { RequestSignature, IHeadersData } from '../api/request-signature';
/**
 * ObjectPurchaseApi - axios parameter creator
 */
export const ObjectPurchaseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Download multiples attachments from a Purchase
         * @param {number} pkiPurchaseID 
         * @param {PurchaseBatchDownloadV1Request} purchaseBatchDownloadV1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purchaseBatchDownloadV1: async (pkiPurchaseID: number, purchaseBatchDownloadV1Request: PurchaseBatchDownloadV1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pkiPurchaseID' is not null or undefined
            assertParamExists('purchaseBatchDownloadV1', 'pkiPurchaseID', pkiPurchaseID)
            // verify required parameter 'purchaseBatchDownloadV1Request' is not null or undefined
            assertParamExists('purchaseBatchDownloadV1', 'purchaseBatchDownloadV1Request', purchaseBatchDownloadV1Request)
            const localVarPath = `/1/object/purchase/{pkiPurchaseID}/batchDownload`
                .replace('{pkiPurchaseID}', encodeURIComponent(String(pkiPurchaseID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let basePath = DUMMY_BASE_URL
            if (configuration && configuration.basePath) basePath = configuration.basePath
            //const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            const localVarUrlObj = new URL(localVarPath, basePath);

            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/zip,text/xml,application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            //localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = {...headersFromBaseOptions, ...localVarHeaderParameter,  ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(purchaseBatchDownloadV1Request, localVarRequestOptions, configuration)

            // Signature
            if (configuration && configuration.apiKey) {
                const secret = configuration.getSecret()
                if (secret) {
                    const headers:IHeadersData = {
                        authorization: configuration.apiKey as string,
                        secret: secret as string,
                        method: 'POST' as string,
                        url: basePath + toPathString(localVarUrlObj) as string,
                        body: localVarRequestOptions.data || '' as string
                    }
                    const signatureHeaders = RequestSignature.getHeaders(headers)
                    localVarRequestOptions.headers = { ...localVarRequestOptions.headers, ...signatureHeaders }
                } 
            }

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve Purchase\'s attachments
         * @param {number} pkiPurchaseID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purchaseGetAttachmentsV1: async (pkiPurchaseID: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pkiPurchaseID' is not null or undefined
            assertParamExists('purchaseGetAttachmentsV1', 'pkiPurchaseID', pkiPurchaseID)
            const localVarPath = `/1/object/purchase/{pkiPurchaseID}/getAttachments`
                .replace('{pkiPurchaseID}', encodeURIComponent(String(pkiPurchaseID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let basePath = DUMMY_BASE_URL
            if (configuration && configuration.basePath) basePath = configuration.basePath
            //const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            const localVarUrlObj = new URL(localVarPath, basePath);

            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            //localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = {...headersFromBaseOptions, ...localVarHeaderParameter,  ...options.headers};

            // Signature
            if (configuration && configuration.apiKey) {
                const secret = configuration.getSecret()
                if (secret) {
                    const headers:IHeadersData = {
                        authorization: configuration.apiKey as string,
                        secret: secret as string,
                        method: 'GET' as string,
                        url: basePath + toPathString(localVarUrlObj) as string,
                        body: localVarRequestOptions.data || '' as string
                    }
                    const signatureHeaders = RequestSignature.getHeaders(headers)
                    localVarRequestOptions.headers = { ...localVarRequestOptions.headers, ...signatureHeaders }
                } 
            }

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Import attachments into the Purchase
         * @param {number} pkiPurchaseID 
         * @param {PurchaseImportIntoEDMV1Request} purchaseImportIntoEDMV1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purchaseImportIntoEDMV1: async (pkiPurchaseID: number, purchaseImportIntoEDMV1Request: PurchaseImportIntoEDMV1Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pkiPurchaseID' is not null or undefined
            assertParamExists('purchaseImportIntoEDMV1', 'pkiPurchaseID', pkiPurchaseID)
            // verify required parameter 'purchaseImportIntoEDMV1Request' is not null or undefined
            assertParamExists('purchaseImportIntoEDMV1', 'purchaseImportIntoEDMV1Request', purchaseImportIntoEDMV1Request)
            const localVarPath = `/1/object/purchase/{pkiPurchaseID}/importIntoEDM`
                .replace('{pkiPurchaseID}', encodeURIComponent(String(pkiPurchaseID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let basePath = DUMMY_BASE_URL
            if (configuration && configuration.basePath) basePath = configuration.basePath
            //const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            const localVarUrlObj = new URL(localVarPath, basePath);

            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            //localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.headers = {...headersFromBaseOptions, ...localVarHeaderParameter,  ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(purchaseImportIntoEDMV1Request, localVarRequestOptions, configuration)

            // Signature
            if (configuration && configuration.apiKey) {
                const secret = configuration.getSecret()
                if (secret) {
                    const headers:IHeadersData = {
                        authorization: configuration.apiKey as string,
                        secret: secret as string,
                        method: 'POST' as string,
                        url: basePath + toPathString(localVarUrlObj) as string,
                        body: localVarRequestOptions.data || '' as string
                    }
                    const signatureHeaders = RequestSignature.getHeaders(headers)
                    localVarRequestOptions.headers = { ...localVarRequestOptions.headers, ...signatureHeaders }
                } 
            }

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ObjectPurchaseApi - functional programming interface
 */
export const ObjectPurchaseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ObjectPurchaseApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Download multiples attachments from a Purchase
         * @param {number} pkiPurchaseID 
         * @param {PurchaseBatchDownloadV1Request} purchaseBatchDownloadV1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async purchaseBatchDownloadV1(pkiPurchaseID: number, purchaseBatchDownloadV1Request: PurchaseBatchDownloadV1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.purchaseBatchDownloadV1(pkiPurchaseID, purchaseBatchDownloadV1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObjectPurchaseApi.purchaseBatchDownloadV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve Purchase\'s attachments
         * @param {number} pkiPurchaseID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async purchaseGetAttachmentsV1(pkiPurchaseID: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PurchaseGetAttachmentsV1Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.purchaseGetAttachmentsV1(pkiPurchaseID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObjectPurchaseApi.purchaseGetAttachmentsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Import attachments into the Purchase
         * @param {number} pkiPurchaseID 
         * @param {PurchaseImportIntoEDMV1Request} purchaseImportIntoEDMV1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async purchaseImportIntoEDMV1(pkiPurchaseID: number, purchaseImportIntoEDMV1Request: PurchaseImportIntoEDMV1Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PurchaseImportIntoEDMV1Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.purchaseImportIntoEDMV1(pkiPurchaseID, purchaseImportIntoEDMV1Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObjectPurchaseApi.purchaseImportIntoEDMV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ObjectPurchaseApi - factory interface
 */
export const ObjectPurchaseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ObjectPurchaseApiFp(configuration)
    return {
        /**
         * 
         * @summary Download multiples attachments from a Purchase
         * @param {number} pkiPurchaseID 
         * @param {PurchaseBatchDownloadV1Request} purchaseBatchDownloadV1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purchaseBatchDownloadV1(pkiPurchaseID: number, purchaseBatchDownloadV1Request: PurchaseBatchDownloadV1Request, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.purchaseBatchDownloadV1(pkiPurchaseID, purchaseBatchDownloadV1Request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve Purchase\'s attachments
         * @param {number} pkiPurchaseID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purchaseGetAttachmentsV1(pkiPurchaseID: number, options?: RawAxiosRequestConfig): AxiosPromise<PurchaseGetAttachmentsV1Response> {
            return localVarFp.purchaseGetAttachmentsV1(pkiPurchaseID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Import attachments into the Purchase
         * @param {number} pkiPurchaseID 
         * @param {PurchaseImportIntoEDMV1Request} purchaseImportIntoEDMV1Request 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purchaseImportIntoEDMV1(pkiPurchaseID: number, purchaseImportIntoEDMV1Request: PurchaseImportIntoEDMV1Request, options?: RawAxiosRequestConfig): AxiosPromise<PurchaseImportIntoEDMV1Response> {
            return localVarFp.purchaseImportIntoEDMV1(pkiPurchaseID, purchaseImportIntoEDMV1Request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ObjectPurchaseApi - object-oriented interface
 */
export class ObjectPurchaseApi extends BaseAPI {
    /**
     * 
     * @summary Download multiples attachments from a Purchase
     * @param {number} pkiPurchaseID 
     * @param {PurchaseBatchDownloadV1Request} purchaseBatchDownloadV1Request 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public purchaseBatchDownloadV1(pkiPurchaseID: number, purchaseBatchDownloadV1Request: PurchaseBatchDownloadV1Request, options?: RawAxiosRequestConfig) {
        return ObjectPurchaseApiFp(this.configuration).purchaseBatchDownloadV1(pkiPurchaseID, purchaseBatchDownloadV1Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve Purchase\'s attachments
     * @param {number} pkiPurchaseID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public purchaseGetAttachmentsV1(pkiPurchaseID: number, options?: RawAxiosRequestConfig) {
        return ObjectPurchaseApiFp(this.configuration).purchaseGetAttachmentsV1(pkiPurchaseID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Import attachments into the Purchase
     * @param {number} pkiPurchaseID 
     * @param {PurchaseImportIntoEDMV1Request} purchaseImportIntoEDMV1Request 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public purchaseImportIntoEDMV1(pkiPurchaseID: number, purchaseImportIntoEDMV1Request: PurchaseImportIntoEDMV1Request, options?: RawAxiosRequestConfig) {
        return ObjectPurchaseApiFp(this.configuration).purchaseImportIntoEDMV1(pkiPurchaseID, purchaseImportIntoEDMV1Request, options).then((request) => request(this.axios, this.basePath));
    }
}

